<a href="https://colab.research.google.com/github/LGBFBenchmarking/ChangeLogMaker/blob/main/Automate_differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Test code for automated output file

#Load files

##new_df is new data including new year's data
##diff_df has old data (no changes or new data for the new year)

In [ ]:
import pandas as pd
import numpy as np

def get_data(url): # this function gets data stored as csv file from a given url
  df = pd.read_csv(url)
  return df

In [ ]:
url_old = "https://raw.githubusercontent.com/LGBFBenchmarking/ChangeLogMaker/refs/heads/main/LGBF_Data_Mar26.csv"
url_new = "https://raw.githubusercontent.com/LGBFBenchmarking/ChangeLogMaker/refs/heads/main/LGBF_Data_Apr26.csv"
old_df = get_data(url_old)
new_df = get_data(url_new)

In [ ]:
old_df.dtypes

Code               object
LocalAuthority     object
Year               object
Indicator         float64
Numerator         float64
Denominator       float64
dtype: object

In [ ]:
new_df.dtypes

Code               object
LocalAuthority     object
Year               object
Indicator         float64
Numerator         float64
Denominator       float64
dtype: object

In [ ]:
new_df['Indicator'] = new_df['Indicator'].map("{:.2f}".format)
new_df['Numerator'] = new_df['Numerator'].map('{:.2f}'.format)
new_df['Denominator'] = new_df['Denominator'].map('{:.2f}'.format)

In [ ]:
old_df['Indicator'] = old_df['Indicator'].map('{:.2f}'.format)
old_df['Numerator'] = old_df['Numerator'].map('{:.2f}'.format)
old_df['Denominator'] = old_df['Denominator'].map('{:.2f}'.format)

In [ ]:
old_df = old_df.round(4)
new_df = new_df.round(4)

In [ ]:
df1 = old_df
df2 = new_df

In [ ]:
new_set = df2[~df2.astype(str).apply(tuple, 1).isin(df1.astype(str).apply(tuple, 1))]

In [ ]:
out = pd.merge(old_df, new_df, on=['Code', 'LocalAuthority', 'Year'], how='outer',
               suffixes=('_old', '_new')).set_index(['Code', 'LocalAuthority', 'Year'])

out.columns = pd.MultiIndex.from_tuples(out.columns.str.split('_').map(tuple)).swaplevel()
out

                                   old                             new  \
                             Indicator Numerator Denominator Indicator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11      0.33    637.00  1922292.00      0.33
                     2011-12      0.76   1554.00  2045051.00      0.76
                     2012-13      3.64   7883.00  2163756.00      3.64
                     2013-14      3.48   7726.00  2222588.00      3.48
                     2014-15      3.02   7517.00  2487138.00      3.02
...                                ...       ...         ...       ...
SW08  West Lothian   2020-21    369.62   4692.00    12694.00    369.62
                     2021-22    439.50   5750.00    13083.00    439.50
                     2022-23    639.84   8856.00    13841.00    639.84
                     2023-24    809.85  11742.00    14499.00    809.85
                     2024-25    960.18  14466.00    15066.00    960.18


                             Numerator Denominator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11    637.00  1922292.00
                     2011-12   1554.00  2045051.00
                     2012-13   7883.00  2163756.00
                     2013-14   7726.00  2222588.00
                     2014-15   7517.00  2487138.00
...                                ...         ...
SW08  West Lothian   2020-21   4692.00    12694.00
                     2021-22   5750.00    13083.00
                     2022-23   8856.00    13841.00
                     2023-24  11742.00    14499.00
                     2024-25  14466.00    15066.00

[44676 rows x 6 columns]

In [ ]:
out = out.drop_duplicates(keep=False)
out

                                   old                             new  \
                             Indicator Numerator Denominator Indicator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11      0.33    637.00  1922292.00      0.33
                     2011-12      0.76   1554.00  2045051.00      0.76
                     2012-13      3.64   7883.00  2163756.00      3.64
                     2013-14      3.48   7726.00  2222588.00      3.48
                     2014-15      3.02   7517.00  2487138.00      3.02
...                                ...       ...         ...       ...
SW08  West Lothian   2020-21    369.62   4692.00    12694.00    369.62
                     2021-22    439.50   5750.00    13083.00    439.50
                     2022-23    639.84   8856.00    13841.00    639.84
                     2023-24    809.85  11742.00    14499.00    809.85
                     2024-25    960.18  14466.00    15066.00    960.18


                             Numerator Denominator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11    637.00  1922292.00
                     2011-12   1554.00  2045051.00
                     2012-13   7883.00  2163756.00
                     2013-14   7726.00  2222588.00
                     2014-15   7517.00  2487138.00
...                                ...         ...
SW08  West Lothian   2020-21   4692.00    12694.00
                     2021-22   5750.00    13083.00
                     2022-23   8856.00    13841.00
                     2023-24  11742.00    14499.00
                     2024-25  14466.00    15066.00

[23675 rows x 6 columns]

In [ ]:
new_set

          Code LocalAuthority     Year Indicator  Numerator Denominator
489      C&L02  Aberdeen City  2019-20       nan        nan  1736063.00
490      C&L02  Aberdeen City  2020-21       nan        nan   300291.00
491      C&L02  Aberdeen City  2021-22       nan        nan  1347180.00
504      C&L02  Aberdeenshire  2019-20       nan        nan  2003318.00
505      C&L02  Aberdeenshire  2020-21       nan        nan  1125625.00
...        ...            ...      ...       ...        ...         ...
44095   ECON05       Scotland  2025-26     13.07    7250.00  5546900.00
44185  ECON12a       Scotland  2023-24      0.03  109140.00  3491476.00
44186  ECON12a       Scotland  2024-25      0.03  108550.00  3511191.00
44187  ECON12a       Scotland  2025-26      0.03  110500.00  3511191.00
44203  ECON12b       Scotland  2025-26      0.04   22035.00   592602.00

[646 rows x 6 columns]

In [ ]:
df1.merge(df2, on=['Code','LocalAuthority','Year'], suffixes=['_old','_new']).drop_duplicates(keep= False) # just a test no need to run this!!!

,Code,LocalAuthority,Year,Indicator_old,Numerator_old,Denominator_old,Indicator_new,Numerator_new,Denominator_new
0,C&L01,Aberdeen City,2010-11,0.33,637.00,1922292.00,0.33,637.00,1922292.00
1,C&L01,Aberdeen City,2011-12,0.76,1554.00,2045051.00,0.76,1554.00,2045051.00
2,C&L01,Aberdeen City,2012-13,3.64,7883.00,2163756.00,3.64,7883.00,2163756.00
3,C&L01,Aberdeen City,2013-14,3.48,7726.00,2222588.00,3.48,7726.00,2222588.00
4,C&L01,Aberdeen City,2014-15,3.02,7517.00,2487138.00,3.02,7517.00,2487138.00
...,...,...,...,...,...,...,...,...,...
44440,SW08,Scotland,2020-21,485.45,227524.00,468682.00,485.45,227524.00,468682.00
44441,SW08,Scotland,2021-22,749.73,357719.00,477131.00,749.73,357719.00,477131.00
44442,SW08,Scotland,2022-23,882.88,439596.00,497909.00,882.88,439596.00,497909.00
44443,SW08,Scotland,2023-24,841.47,431429.00,512706.00,841.47,431429.00,512706.00
44444,SW08,Scotland,2024-25,898.95,474153.00,527454.00,898.95,474153.00,527454.00

In [ ]:
def dataframe_difference(df1, df2, which=None):
    """Find rows which are different between two DataFrames."""
    comparison_df = df1.merge(
        df2,
        indicator=True,
        how='outer'
    )
    if which is None:
        diff_df = comparison_df[comparison_df['_merge'] != 'both']  # Identify data changes/updates
    else:
        diff_df = comparison_df[comparison_df['_merge'] == which]
    return diff_df

In [ ]:
def getColChangedName(row):
    colsChanged = []
    for c in df1.columns.values:
        if row[c+"_diff"] == True:
            colsChanged.append(c)
    return ", ".join(colsChanged)

In [ ]:
df1 = old_df.set_index(['Code', 'LocalAuthority', 'Year'])
df2 = new_set.set_index(['Code','LocalAuthority', 'Year'])

diffs = df1.merge(df2, left_index=True, right_index=True, suffixes=('_old', '_new'))

diff_cols = [c+"_diff" for c in df1.columns.values]

diffs

                               Indicator_old Numerator_old Denominator_old  \
Code    LocalAuthority Year
C&L02   Aberdeen City  2019-20          2.17       3764.00      1736063.00
                       2020-21         10.74       3225.00       300291.00
                       2021-22          2.45       3300.00      1347180.00
        Aberdeenshire  2019-20          1.91       3818.00      2003318.00
                       2020-21          3.36       3783.00      1125625.00
...                                      ...           ...             ...
ECON05  Scotland       2022-23         14.42       7853.00      5447000.00
                       2023-24         13.53       7451.00      5506000.00
                       2024-25         12.26       6799.00      5546900.00
ECON12a Scotland       2023-24          0.03     109135.00      3491476.00
                       2024-25          0.03     108540.00      3511191.00

                               Indicator_new Numerator_new Denominator_new
Code    LocalAuthority Year
C&L02   Aberdeen City  2019-20           nan           nan      1736063.00
                       2020-21           nan           nan       300291.00
                       2021-22           nan           nan      1347180.00
        Aberdeenshire  2019-20           nan           nan      2003318.00
                       2020-21           nan           nan      1125625.00
...                                      ...           ...             ...
ECON05  Scotland       2022-23         14.41       7850.00      5447000.00
                       2023-24         13.53       7449.00      5506000.00
                       2024-25         13.43       7449.00      5546900.00
ECON12a Scotland       2023-24          0.03     109140.00      3491476.00
                       2024-25          0.03     108550.00      3511191.00

[415 rows x 6 columns]

In [ ]:
#from google.colab import files
#diffs. to_excel('diffs.xlsx')
#files.download('diffs.xlsx')

In [ ]:
temp = new_df.rename({'Year': 'Year_new'}, axis=1)
temp

        Code LocalAuthority Year_new Indicator  Numerator Denominator
0      C&L01  Aberdeen City  2010-11      0.33     637.00  1922292.00
1      C&L01  Aberdeen City  2011-12      0.76    1554.00  2045051.00
2      C&L01  Aberdeen City  2012-13      3.64    7883.00  2163756.00
3      C&L01  Aberdeen City  2013-14      3.48    7726.00  2222588.00
4      C&L01  Aberdeen City  2014-15      3.02    7517.00  2487138.00
...      ...            ...      ...       ...        ...         ...
44671   SW08       Scotland  2020-21    485.45  227524.00   468682.00
44672   SW08       Scotland  2021-22    749.73  357719.00   477131.00
44673   SW08       Scotland  2022-23    882.88  439596.00   497909.00
44674   SW08       Scotland  2023-24    841.47  431429.00   512706.00
44675   SW08       Scotland  2024-25    898.95  474153.00   527454.00

[44676 rows x 6 columns]

In [ ]:
#find rows with added data from new year
temp = new_df.rename({'Year': 'Year_new'}, axis=1)
#merged = temp.merge(old_df, how='left', left_on=['LocalAuthority','Code','Year_new'], right_on=['LocalAuthority','Code','Year'])
merged = temp.merge(old_df, how='left', left_on=['LocalAuthority','Year_new'], right_on=['LocalAuthority','Year'],indicator='Match')
new_year_df = np.where(merged['Year'].isnull())[0]
new_year_df

array([2295157, 2296251, 2297346, 2298385, 2299471, 2300515, 2301610,
       2302705, 2303799, 2304889, 2305977, 2307071, 2308035, 2309127,
       2310222, 2311266, 2312352, 2313393, 2314484, 2315550, 2316642,
       2317737, 2318768, 2319862, 2320956, 2321999, 2323015, 2324108,
       2325203, 2326295, 2327387, 2328482, 2549607, 2550972, 2552341,
       2553650, 2555010, 2556324, 2557693, 2559062, 2560430, 2561793,
       2563155, 2564522, 2565742, 2567108, 2568477, 2569791, 2571151,
       2572462, 2573827, 2575162, 2576528, 2577897, 2579190, 2580558,
       2581926, 2583237, 2584514, 2585881, 2587250, 2588616, 2589982,
       2591351, 2592716, 2594081, 2595450, 2596759, 2598119, 2599433,
       2600802, 2602171, 2603539, 2604902, 2606264, 2607631, 2608851,
       2610217, 2611586, 2612900, 2614260, 2615571, 2616936, 2618271,
       2619637, 2621006, 2622299, 2623667, 2625035, 2626346, 2627623,
       2628990, 2630359, 2631725, 2633091, 2634460, 4065474, 4074105,
       4075474])

# create a new data frame with just the new year's data

In [ ]:
#new year added data
new_Data = pd.concat([old_df,new_df]).drop_duplicates(subset=["Code", "LocalAuthority", 'Year'], keep=False)

In [ ]:
new_Data

          Code    LocalAuthority     Year Indicator  Numerator Denominator
7547     CHN09     Aberdeen City  2024-25      0.87        nan         nan
7562     CHN09     Aberdeenshire  2024-25      0.76        nan         nan
7577     CHN09             Angus  2024-25      0.87        nan         nan
7592     CHN09     Argyll & Bute  2024-25      0.79        nan         nan
7607     CHN09  Clackmannanshire  2024-25      0.93        nan         nan
...        ...               ...      ...       ...        ...         ...
43770    CHN22          Scotland  2024-25      0.07        nan         nan
43785    CHN23          Scotland  2024-25      0.17        nan         nan
44095   ECON05          Scotland  2025-26     13.07    7250.00  5546900.00
44187  ECON12a          Scotland  2025-26      0.03  110500.00  3511191.00
44203  ECON12b          Scotland  2025-26      0.04   22035.00   592602.00

[231 rows x 6 columns]

In [ ]:
new_Data.rename(columns={'Indicator': 'Indicator_new', 'Numerator': 'Numerator_new','Denominator': 'Denominator_new'}, inplace=True)

In [ ]:
#from google.colab import files
#new_Data. to_excel('new_Data.xlsx')
#files.download('new_Data.xlsx')

#Time to create the change log
##Standardise column names

In [ ]:
diffs.columns = diffs.columns.str.strip()
new_Data.columns = new_Data.columns.str.strip()

In [ ]:
diffs

                               Indicator_old Numerator_old Denominator_old  \
Code    LocalAuthority Year
C&L02   Aberdeen City  2019-20          2.17       3764.00      1736063.00
                       2020-21         10.74       3225.00       300291.00
                       2021-22          2.45       3300.00      1347180.00
        Aberdeenshire  2019-20          1.91       3818.00      2003318.00
                       2020-21          3.36       3783.00      1125625.00
...                                      ...           ...             ...
ECON05  Scotland       2022-23         14.42       7853.00      5447000.00
                       2023-24         13.53       7451.00      5506000.00
                       2024-25         12.26       6799.00      5546900.00
ECON12a Scotland       2023-24          0.03     109135.00      3491476.00
                       2024-25          0.03     108540.00      3511191.00

                               Indicator_new Numerator_new Denominator_new
Code    LocalAuthority Year
C&L02   Aberdeen City  2019-20           nan           nan      1736063.00
                       2020-21           nan           nan       300291.00
                       2021-22           nan           nan      1347180.00
        Aberdeenshire  2019-20           nan           nan      2003318.00
                       2020-21           nan           nan      1125625.00
...                                      ...           ...             ...
ECON05  Scotland       2022-23         14.41       7850.00      5447000.00
                       2023-24         13.53       7449.00      5506000.00
                       2024-25         13.43       7449.00      5546900.00
ECON12a Scotland       2023-24          0.03     109140.00      3491476.00
                       2024-25          0.03     108550.00      3511191.00

[415 rows x 6 columns]

##Rename columns (diffs → final format)

In [ ]:
diffs_renamed = diffs.reindex(columns=['Indicator Code','LocalAuthority',	'Year',	'Indicator old value',	'Numerator old value',	'Denominator old value','Indicator new value',	'Numerator new value',	'Denominator new value'])

In [ ]:
new_data_renamed = new_Data.rename(columns={ "Code": "Indicator Code"})

In [ ]:
# Add missing OLD columns (since these are new entries)
new_data_renamed["Indicator old value"] = pd.NA
new_data_renamed["Numerator old value"] = pd.NA
new_data_renamed["Denominator old value"] = pd.NA

In [ ]:
new_data_renamed

,Indicator Code,LocalAuthority,Year,Indicator_new,Numerator_new,Denominator_new,Indicator old value,Numerator old value,Denominator old value
7547,CHN09,Aberdeen City,2024-25,0.87,nan,nan,<NA>,<NA>,<NA>
7562,CHN09,Aberdeenshire,2024-25,0.76,nan,nan,<NA>,<NA>,<NA>
7577,CHN09,Angus,2024-25,0.87,nan,nan,<NA>,<NA>,<NA>
7592,CHN09,Argyll & Bute,2024-25,0.79,nan,nan,<NA>,<NA>,<NA>
7607,CHN09,Clackmannanshire,2024-25,0.93,nan,nan,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...
43770,CHN22,Scotland,2024-25,0.07,nan,nan,<NA>,<NA>,<NA>
43785,CHN23,Scotland,2024-25,0.17,nan,nan,<NA>,<NA>,<NA>
44095,ECON05,Scotland,2025-26,13.07,7250.00,5546900.00,<NA>,<NA>,<NA>
44187,ECON12a,Scotland,2025-26,0.03,110500.00,3511191.00,<NA>,<NA>,<NA>
44203,ECON12b,Scotland,2025-26,0.04,22035.00,592602.00,<NA>,<NA>,<NA>

In [ ]:
key_cols = ["Indicator Code", "LocalAuthority", "Year"]

In [ ]:
# Create key to compare
diffs_keys = diffs_renamed[key_cols].astype(str).agg("|".join, axis=1)
new_keys = new_data_renamed[key_cols].astype(str).agg("|".join, axis=1)

In [ ]:
new_rows_mask = ~new_keys.isin(diffs_keys)
new_rows = new_data_renamed[new_rows_mask].copy()

# Rename new_data columns to match changelog
new_rows = new_rows.rename(columns={
    "Code": "Indicator Code",
    "Indicator_new": "Indicator new value",
    "Numerator_new": "Numerator new value",
    "Denominator_new": "Denominator new value"
})

In [ ]:
# Keep only required columns

new_rows = new_rows[[
    "Indicator Code",
    "LocalAuthority",
    "Year",
    "Indicator new value",
    "Indicator old value",
    "Numerator new value",
    "Numerator old value",
    "Denominator new value",
    "Denominator old value"
]]

In [ ]:
new_rows

,Indicator Code,LocalAuthority,Year,Indicator new value,Indicator old value,Numerator new value,Numerator old value,Denominator new value,Denominator old value
7547,CHN09,Aberdeen City,2024-25,0.87,<NA>,nan,<NA>,nan,<NA>
7562,CHN09,Aberdeenshire,2024-25,0.76,<NA>,nan,<NA>,nan,<NA>
7577,CHN09,Angus,2024-25,0.87,<NA>,nan,<NA>,nan,<NA>
7592,CHN09,Argyll & Bute,2024-25,0.79,<NA>,nan,<NA>,nan,<NA>
7607,CHN09,Clackmannanshire,2024-25,0.93,<NA>,nan,<NA>,nan,<NA>
...,...,...,...,...,...,...,...,...,...
43770,CHN22,Scotland,2024-25,0.07,<NA>,nan,<NA>,nan,<NA>
43785,CHN23,Scotland,2024-25,0.17,<NA>,nan,<NA>,nan,<NA>
44095,ECON05,Scotland,2025-26,13.07,<NA>,7250.00,<NA>,5546900.00,<NA>
44187,ECON12a,Scotland,2025-26,0.03,<NA>,110500.00,<NA>,3511191.00,<NA>
44203,ECON12b,Scotland,2025-26,0.04,<NA>,22035.00,<NA>,592602.00,<NA>

In [ ]:
changelog = pd.concat([diffs_renamed, new_rows], ignore_index=True)

In [ ]:
changelog

,Indicator Code,LocalAuthority,Year,Indicator old value,Numerator old value,Denominator old value,Indicator new value,Numerator new value,Denominator new value
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
641,CHN22,Scotland,2024-25,NaN,NaN,NaN,0.07,nan,nan
642,CHN23,Scotland,2024-25,NaN,NaN,NaN,0.17,nan,nan
643,ECON05,Scotland,2025-26,NaN,NaN,NaN,13.07,7250.00,5546900.00
644,ECON12a,Scotland,2025-26,NaN,NaN,NaN,0.03,110500.00,3511191.00
645,ECON12b,Scotland,2025-26,NaN,NaN,NaN,0.04,22035.00,592602.00

In [ ]:
from google.colab import files
new_Data. to_excel('changelog.xlsx')
files.download('changelog.xlsx')