<a href="https://colab.research.google.com/github/LGBFBenchmarking/ChangeLogMaker/blob/main/Automate_differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Test code for automated output file

#Load files

##new_df is new data including new year's data
##diff_df has old data (no changes or new data for the new year)

In [1]:
import pandas as pd
import numpy as np

def get_data(url): # this function gets data stored as csv file from a given url
  df = pd.read_csv(url)
  return df

In [2]:
url_old = "https://raw.githubusercontent.com/LGBFBenchmarking/ChangeLogMaker/refs/heads/main/LGBF_Data_Nov_2025.csv"
url_new = "https://raw.githubusercontent.com/LGBFBenchmarking/ChangeLogMaker/refs/heads/main/LGBF_Data_Dec_2025.csv"
old_df = get_data(url_old)
new_df = get_data(url_new)

In [3]:
old_df.dtypes

Code               object
LocalAuthority     object
Year               object
Indicator         float64
Numerator         float64
Denominator       float64
dtype: object

In [4]:
new_df.dtypes

Code               object
LocalAuthority     object
Year               object
Indicator         float64
Numerator         float64
Denominator       float64
dtype: object

In [5]:
new_df['Indicator'] = new_df['Indicator'].map("{:.2f}".format)
new_df['Numerator'] = new_df['Numerator'].map('{:.2f}'.format)
new_df['Denominator'] = new_df['Denominator'].map('{:.2f}'.format)

In [6]:
old_df['Indicator'] = old_df['Indicator'].map('{:.2f}'.format)
old_df['Numerator'] = old_df['Numerator'].map('{:.2f}'.format)
old_df['Denominator'] = old_df['Denominator'].map('{:.2f}'.format)

In [7]:
old_df = old_df.round(4)
new_df = new_df.round(4)

In [8]:
old_df.head()

    Code LocalAuthority     Year Indicator Numerator Denominator
0  C&L01  Aberdeen City  2010-11      0.33    637.00  1922292.00
1  C&L01  Aberdeen City  2011-12      0.76   1554.00  2045051.00
2  C&L01  Aberdeen City  2012-13      3.64   7883.00  2163756.00
3  C&L01  Aberdeen City  2013-14      3.48   7726.00  2222588.00
4  C&L01  Aberdeen City  2014-15      3.02   7517.00  2487138.00

In [9]:
new_df.head()

    Code LocalAuthority     Year Indicator Numerator Denominator
0  C&L01  Aberdeen City  2010-11      0.33    637.00  1922292.00
1  C&L01  Aberdeen City  2011-12      0.76   1554.00  2045051.00
2  C&L01  Aberdeen City  2012-13      3.64   7883.00  2163756.00
3  C&L01  Aberdeen City  2013-14      3.48   7726.00  2222588.00
4  C&L01  Aberdeen City  2014-15      3.02   7517.00  2487138.00

In [10]:
df1 = old_df
df2 = new_df

In [11]:
new_set = df2[~df2.astype(str).apply(tuple, 1).isin(df1.astype(str).apply(tuple, 1))]

In [12]:
out = pd.merge(old_df, new_df, on=['Code', 'LocalAuthority', 'Year'], how='outer',
               suffixes=('_old', '_new')).set_index(['Code', 'LocalAuthority', 'Year'])

out.columns = pd.MultiIndex.from_tuples(out.columns.str.split('_').map(tuple)).swaplevel()
out

                                   old                             new  \
                             Indicator Numerator Denominator Indicator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11      0.33    637.00  1922292.00      0.33
                     2011-12      0.76   1554.00  2045051.00      0.76
                     2012-13      3.64   7883.00  2163756.00      3.64
                     2013-14      3.48   7726.00  2222588.00      3.48
                     2014-15      3.02   7517.00  2487138.00      3.02
...                                ...       ...         ...       ...
SW08  West Lothian   2020-21       NaN       NaN         NaN    359.60
                     2021-22       NaN       NaN         NaN    426.37
                     2022-23       NaN       NaN         NaN    676.96
                     2023-24       NaN       NaN         NaN    848.35
                     2024-25       NaN       NaN         NaN    998.69


                             Numerator Denominator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11    637.00  1922292.00
                     2011-12   1554.00  2045051.00
                     2012-13   7883.00  2163756.00
                     2013-14   7726.00  2222588.00
                     2014-15   7517.00  2487138.00
...                                ...         ...
SW08  West Lothian   2020-21   4692.00    13048.00
                     2021-22   5750.00    13486.00
                     2022-23   8856.00    13082.00
                     2023-24  11742.00    13841.00
                     2024-25  14466.00    14485.00

[44164 rows x 6 columns]

In [13]:
out = out.drop_duplicates(keep=False)
out

                                   old                             new  \
                             Indicator Numerator Denominator Indicator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11      0.33    637.00  1922292.00      0.33
                     2011-12      0.76   1554.00  2045051.00      0.76
                     2012-13      3.64   7883.00  2163756.00      3.64
                     2013-14      3.48   7726.00  2222588.00      3.48
                     2014-15      3.02   7517.00  2487138.00      3.02
...                                ...       ...         ...       ...
SW08  West Lothian   2020-21       NaN       NaN         NaN    359.60
                     2021-22       NaN       NaN         NaN    426.37
                     2022-23       NaN       NaN         NaN    676.96
                     2023-24       NaN       NaN         NaN    848.35
                     2024-25       NaN       NaN         NaN    998.69


                             Numerator Denominator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11    637.00  1922292.00
                     2011-12   1554.00  2045051.00
                     2012-13   7883.00  2163756.00
                     2013-14   7726.00  2222588.00
                     2014-15   7517.00  2487138.00
...                                ...         ...
SW08  West Lothian   2020-21   4692.00    13048.00
                     2021-22   5750.00    13486.00
                     2022-23   8856.00    13082.00
                     2023-24  11742.00    13841.00
                     2024-25  14466.00    14485.00

[23454 rows x 6 columns]

In [14]:
new_set

        Code     LocalAuthority     Year Indicator  Numerator Denominator
434    C&L01  South Lanarkshire  2024-25      4.28   11170.00  2608331.00
1034   C&L03   Clackmannanshire  2024-25       nan      29.00         nan
1123   C&L03  East Renfrewshire  2023-24       nan        nan         nan
1124   C&L03  East Renfrewshire  2024-25       nan        nan         nan
1241   C&L03         Midlothian  2021-22       nan      30.00         nan
...      ...                ...      ...       ...        ...         ...
44159   SW08           Scotland  2020-21    484.28  227524.00   469817.00
44160   SW08           Scotland  2021-22    747.92  357719.00   478283.00
44161   SW08           Scotland  2022-23    921.38  439596.00   477105.00
44162   SW08           Scotland  2023-24    866.48  431429.00   497909.00
44163   SW08           Scotland  2024-25    924.79  474153.00   512713.00

[2934 rows x 6 columns]

In [15]:
from google.colab import files
new_set. to_excel('new_set.xlsx')
files.download('new_set.xlsx')

In [16]:
df1.merge(df2, on=['Code','LocalAuthority','Year'], suffixes=['_old','_new']).drop_duplicates(keep= False) # just a test no need to run this!!!

,Code,LocalAuthority,Year,Indicator_old,Numerator_old,Denominator_old,Indicator_new,Numerator_new,Denominator_new
0,C&L01,Aberdeen City,2010-11,0.33,637.00,1922292.00,0.33,637.00,1922292.00
1,C&L01,Aberdeen City,2011-12,0.76,1554.00,2045051.00,0.76,1554.00,2045051.00
2,C&L01,Aberdeen City,2012-13,3.64,7883.00,2163756.00,3.64,7883.00,2163756.00
3,C&L01,Aberdeen City,2013-14,3.48,7726.00,2222588.00,3.48,7726.00,2222588.00
4,C&L01,Aberdeen City,2014-15,3.02,7517.00,2487138.00,3.02,7517.00,2487138.00
...,...,...,...,...,...,...,...,...,...
41395,SW07,Scotland,2020-21,0.82,nan,nan,0.82,nan,nan
41396,SW07,Scotland,2021-22,0.76,nan,nan,0.76,nan,nan
41397,SW07,Scotland,2022-23,0.75,nan,nan,0.75,nan,nan
41398,SW07,Scotland,2023-24,0.77,nan,nan,0.77,nan,nan
41399,SW07,Scotland,2024-25,0.82,nan,nan,0.82,nan,nan

In [17]:
def dataframe_difference(df1, df2, which=None):
    """Find rows which are different between two DataFrames."""
    comparison_df = df1.merge(
        df2,
        indicator=True,
        how='outer'
    )
    if which is None:
        diff_df = comparison_df[comparison_df['_merge'] != 'both']  # Identify data changes/updates
    else:
        diff_df = comparison_df[comparison_df['_merge'] == which]
    return diff_df

In [18]:
def getColChangedName(row):
    colsChanged = []
    for c in df1.columns.values:
        if row[c+"_diff"] == True:
            colsChanged.append(c)
    return ", ".join(colsChanged)

In [19]:
df1 = old_df.set_index(['Code', 'LocalAuthority', 'Year'])
df2 = new_set.set_index(['Code','LocalAuthority', 'Year'])

diffs = df1.merge(df2, left_index=True, right_index=True, suffixes=('_old', '_new'))

diff_cols = [c+"_diff" for c in df1.columns.values]

for c in df1.columns.values:
    diffs[c+"_diff"] = diffs[c+"_old"] != diffs[c+"_new"]

diffs["Record_Changed"] = diffs[diff_cols].sum(axis=1)/len(diff_cols) > 0


diffs = diffs[diffs["Record_Changed"] == 1]
diffs["Cols_Changed"] = diffs.apply(lambda row: getColChangedName(row), axis=1)

diffs

                                 Indicator_old Numerator_old Denominator_old  \
Code   LocalAuthority    Year
C&L01  South Lanarkshire 2024-25          2.36       6167.00      2608331.00
C&L03  Clackmannanshire  2024-25           nan         29.00            0.00
       East Renfrewshire 2023-24           nan           nan            0.00
                         2024-25           nan           nan            0.00
       Midlothian        2021-22           nan         30.00            0.00
...                                        ...           ...             ...
ENV03a Scotland          2022-23      14341.11      78116.00      5447000.00
                         2023-24      15960.91      87627.00      5490100.00
                         2024-25      17725.76      98323.00      5546900.00
SW02   Scotland          2019-20          0.08     265984.00      3458888.25
                         2024-25          0.09     456553.71      4844069.19

                                 Indicator_new Numerator_new Denominator_new  \
Code   LocalAuthority    Year
C&L01  South Lanarkshire 2024-25          4.28      11170.00      2608331.00
C&L03  Clackmannanshire  2024-25           nan         29.00             nan
       East Renfrewshire 2023-24           nan           nan             nan
                         2024-25           nan           nan             nan
       Midlothian        2021-22           nan         30.00             nan
...                                        ...           ...             ...
ENV03a Scotland          2022-23      15530.93      84597.00      5447000.00
                         2023-24      17055.24      93635.00      5490100.00
                         2024-25      17616.33      97716.00      5546900.00
SW02   Scotland          2019-20          0.08     265984.00      3458888.24
                         2024-25          0.09     456553.71      4842964.19

                                  Indicator_diff  Numerator_diff  \
Code   LocalAuthority    Year
C&L01  South Lanarkshire 2024-25            True            True
C&L03  Clackmannanshire  2024-25           False           False
       East Renfrewshire 2023-24           False           False
                         2024-25           False           False
       Midlothian        2021-22           False           False
...                                          ...             ...
ENV03a Scotland          2022-23            True            True
                         2023-24            True            True
                         2024-25            True            True
SW02   Scotland          2019-20           False           False
                         2024-25           False           False

                                  Denominator_diff  Record_Changed  \
Code   LocalAuthority    Year
C&L01  South Lanarkshire 2024-25             False            True
C&L03  Clackmannanshire  2024-25              True            True
       East Renfrewshire 2023-24              True            True
                         2024-25              True            True
       Midlothian        2021-22              True            True
...                                            ...             ...
ENV03a Scotland          2022-23             False            True
                         2023-24             False            True
                         2024-25             False            True
SW02   Scotland          2019-20              True            True
                         2024-25              True            True

                                          Cols_Changed
Code   LocalAuthority    Year
C&L01  South Lanarkshire 2024-25  Indicator, Numerator
C&L03  Clackmannanshire  2024-25           Denominator
       East Renfrewshire 2023-24           Denominator
                         2024-25           Denominator
       Midlothian        2021-22           Denominator
...                                                ...
ENV03a Scotland          2022-23  Indicator, Numerator
                         2023-24  Indicator, Numerator
                         2024-25  Indicator, Numerator
SW02   Scotland          2019-20           Denominator
                         2024-25           Denominator

[170 rows x 11 columns]

In [20]:
from google.colab import files
diffs. to_excel('diffs.xlsx')
files.download('diffs.xlsx')

In [21]:
old_df

        Code LocalAuthority     Year Indicator Numerator Denominator
0      C&L01  Aberdeen City  2010-11      0.33    637.00  1922292.00
1      C&L01  Aberdeen City  2011-12      0.76   1554.00  2045051.00
2      C&L01  Aberdeen City  2012-13      3.64   7883.00  2163756.00
3      C&L01  Aberdeen City  2013-14      3.48   7726.00  2222588.00
4      C&L01  Aberdeen City  2014-15      3.02   7517.00  2487138.00
...      ...            ...      ...       ...       ...         ...
41395   SW07       Scotland  2020-21      0.82       nan         nan
41396   SW07       Scotland  2021-22      0.76       nan         nan
41397   SW07       Scotland  2022-23      0.75       nan         nan
41398   SW07       Scotland  2023-24      0.77       nan         nan
41399   SW07       Scotland  2024-25      0.82       nan         nan

[41400 rows x 6 columns]

In [22]:
temp = new_df.rename({'Year': 'Year_new'}, axis=1)
temp

        Code LocalAuthority Year_new Indicator  Numerator Denominator
0      C&L01  Aberdeen City  2010-11      0.33     637.00  1922292.00
1      C&L01  Aberdeen City  2011-12      0.76    1554.00  2045051.00
2      C&L01  Aberdeen City  2012-13      3.64    7883.00  2163756.00
3      C&L01  Aberdeen City  2013-14      3.48    7726.00  2222588.00
4      C&L01  Aberdeen City  2014-15      3.02    7517.00  2487138.00
...      ...            ...      ...       ...        ...         ...
44159   SW08       Scotland  2020-21    484.28  227524.00   469817.00
44160   SW08       Scotland  2021-22    747.92  357719.00   478283.00
44161   SW08       Scotland  2022-23    921.38  439596.00   477105.00
44162   SW08       Scotland  2023-24    866.48  431429.00   497909.00
44163   SW08       Scotland  2024-25    924.79  474153.00   512713.00

[44164 rows x 6 columns]

In [23]:
old_df

        Code LocalAuthority     Year Indicator Numerator Denominator
0      C&L01  Aberdeen City  2010-11      0.33    637.00  1922292.00
1      C&L01  Aberdeen City  2011-12      0.76   1554.00  2045051.00
2      C&L01  Aberdeen City  2012-13      3.64   7883.00  2163756.00
3      C&L01  Aberdeen City  2013-14      3.48   7726.00  2222588.00
4      C&L01  Aberdeen City  2014-15      3.02   7517.00  2487138.00
...      ...            ...      ...       ...       ...         ...
41395   SW07       Scotland  2020-21      0.82       nan         nan
41396   SW07       Scotland  2021-22      0.76       nan         nan
41397   SW07       Scotland  2022-23      0.75       nan         nan
41398   SW07       Scotland  2023-24      0.77       nan         nan
41399   SW07       Scotland  2024-25      0.82       nan         nan

[41400 rows x 6 columns]

In [24]:
#find rows with added data from new year
temp = new_df.rename({'Year': 'Year_new'}, axis=1)
#merged = temp.merge(old_df, how='left', left_on=['LocalAuthority','Code','Year_new'], right_on=['LocalAuthority','Code','Year'])
merged = temp.merge(old_df, how='left', left_on=['LocalAuthority','Year_new'], right_on=['LocalAuthority','Year'],indicator='Match')
new_year_df = np.where(merged['Year'].isnull())[0]
new_year_df

array([], dtype=int64)

# create a new data frame with just the new year's data

In [25]:
#new year added data
new_Data = pd.concat([old_df,new_df]).drop_duplicates(subset=["Code", "LocalAuthority", 'Year'], keep=False)

In [26]:
new_Data

         Code    LocalAuthority     Year Indicator  Numerator Denominator
1931   C&L05a     Aberdeen City  2024-25      0.66        nan         nan
1943   C&L05a     Aberdeenshire  2024-25      0.64        nan         nan
1955   C&L05a             Angus  2024-25      0.64        nan         nan
1967   C&L05a     Argyll & Bute  2024-25      0.73        nan         nan
1979   C&L05a  Clackmannanshire  2024-25      0.65        nan         nan
...       ...               ...      ...       ...        ...         ...
44159    SW08          Scotland  2020-21    484.28  227524.00   469817.00
44160    SW08          Scotland  2021-22    747.92  357719.00   478283.00
44161    SW08          Scotland  2022-23    921.38  439596.00   477105.00
44162    SW08          Scotland  2023-24    866.48  431429.00   497909.00
44163    SW08          Scotland  2024-25    924.79  474153.00   512713.00

[2764 rows x 6 columns]

In [27]:
from google.colab import files
new_Data. to_excel('new_Data.xlsx')
files.download('new_Data.xlsx')

#Use diff and new_Data to get the Change log