<a href="https://colab.research.google.com/github/LGBFBenchmarking/ChangeLogMaker/blob/main/Automate_differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Test code for automated output file

#Load files

##new_df is new data including new year's data
##diff_df has old data (no changes or new data for the new year)

In [1]:
import pandas as pd
import numpy as np

def get_data(url): # this function gets data stored as csv file from a given url
  df = pd.read_csv(url)
  return df

In [2]:
url_new = "https://raw.githubusercontent.com/LGBFBenchmarking/ChangeLogMaker/refs/heads/main/LGBF_Data_Nov_2025.csv"
url_old = "https://raw.githubusercontent.com/LGBFBenchmarking/ChangeLogMaker/refs/heads/main/LGBF_data_Oct_2025.csv"
old_df = get_data(url_old)
new_df = get_data(url_new)

In [3]:
old_df.dtypes

Code               object
LocalAuthority     object
Year               object
Indicator         float64
Numerator         float64
Denominator       float64
dtype: object

In [4]:
new_df.dtypes

Code               object
LocalAuthority     object
Year               object
Indicator         float64
Numerator         float64
Denominator       float64
dtype: object

In [5]:
new_df['Indicator'] = new_df['Indicator'].map("{:.2f}".format)
new_df['Numerator'] = new_df['Numerator'].map('{:.2f}'.format)
new_df['Denominator'] = new_df['Denominator'].map('{:.2f}'.format)

In [6]:
old_df['Indicator'] = old_df['Indicator'].map('{:.2f}'.format)
old_df['Numerator'] = old_df['Numerator'].map('{:.2f}'.format)
old_df['Denominator'] = old_df['Denominator'].map('{:.2f}'.format)

In [7]:
old_df = old_df.round(4)
new_df = new_df.round(4)

In [8]:
old_df.head()

    Code LocalAuthority     Year Indicator Numerator Denominator
0  C&L01  Aberdeen City  2010-11      0.33    637.00  1922292.00
1  C&L01  Aberdeen City  2011-12      0.76   1554.00  2045051.00
2  C&L01  Aberdeen City  2012-13      3.64   7883.00  2163756.00
3  C&L01  Aberdeen City  2013-14      3.48   7726.00  2222588.00
4  C&L01  Aberdeen City  2014-15      3.02   7517.00  2487138.00

In [9]:
new_df.head()

    Code LocalAuthority     Year Indicator Numerator Denominator
0  C&L01  Aberdeen City  2010-11      0.33    637.00  1922292.00
1  C&L01  Aberdeen City  2011-12      0.76   1554.00  2045051.00
2  C&L01  Aberdeen City  2012-13      3.64   7883.00  2163756.00
3  C&L01  Aberdeen City  2013-14      3.48   7726.00  2222588.00
4  C&L01  Aberdeen City  2014-15      3.02   7517.00  2487138.00

In [10]:
df1 = old_df
df2 = new_df

In [11]:
new_set = df2[~df2.astype(str).apply(tuple, 1).isin(df1.astype(str).apply(tuple, 1))]

In [12]:
out = pd.merge(old_df, new_df, on=['Code', 'LocalAuthority', 'Year'], how='outer',
               suffixes=('_old', '_new')).set_index(['Code', 'LocalAuthority', 'Year'])

out.columns = pd.MultiIndex.from_tuples(out.columns.str.split('_').map(tuple)).swaplevel()
out

                                   old                             new  \
                             Indicator Numerator Denominator Indicator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11      0.33    637.00  1922292.00      0.33
                     2011-12      0.76   1554.00  2045051.00      0.76
                     2012-13      3.64   7883.00  2163756.00      3.64
                     2013-14      3.48   7726.00  2222588.00      3.48
                     2014-15      3.02   7517.00  2487138.00      3.02
...                                ...       ...         ...       ...
SW07  West Lothian   2020-21      0.84       nan         nan      0.84
                     2021-22      0.81       nan         nan      0.81
                     2022-23      0.76       nan         nan      0.76
                     2023-24      0.85       nan         nan      0.85
                     2024-25      0.86       nan         nan      0.86


                             Numerator Denominator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11    637.00  1922292.00
                     2011-12   1554.00  2045051.00
                     2012-13   7883.00  2163756.00
                     2013-14   7726.00  2222588.00
                     2014-15   7517.00  2487138.00
...                                ...         ...
SW07  West Lothian   2020-21       nan         nan
                     2021-22       nan         nan
                     2022-23       nan         nan
                     2023-24       nan         nan
                     2024-25       nan         nan

[41427 rows x 6 columns]

In [13]:
out = out.drop_duplicates(keep=False)
out

                                   old                             new  \
                             Indicator Numerator Denominator Indicator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11      0.33    637.00  1922292.00      0.33
                     2011-12      0.76   1554.00  2045051.00      0.76
                     2012-13      3.64   7883.00  2163756.00      3.64
                     2013-14      3.48   7726.00  2222588.00      3.48
                     2014-15      3.02   7517.00  2487138.00      3.02
...                                ...       ...         ...       ...
SW06  West Lothian   2020-21    123.34   3518.00    28523.00    123.34
                     2021-22    107.50   3519.00    32735.00    107.50
                     2022-23     95.27   3086.00    32391.00     95.27
                     2023-24     94.12   3380.00    35910.00     94.12
                     2024-25     89.91   3212.00    35726.00     89.91


                             Numerator Denominator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11    637.00  1922292.00
                     2011-12   1554.00  2045051.00
                     2012-13   7883.00  2163756.00
                     2013-14   7726.00  2222588.00
                     2014-15   7517.00  2487138.00
...                                ...         ...
SW06  West Lothian   2020-21   3518.00    28523.00
                     2021-22   3519.00    32735.00
                     2022-23   3086.00    32391.00
                     2023-24   3380.00    35910.00
                     2024-25   3212.00    35726.00

[21129 rows x 6 columns]

In [14]:
new_set

        Code    LocalAuthority     Year Indicator   Numerator Denominator
14     C&L01     Aberdeen City  2024-25      2.19     4335.00  1978218.00
29     C&L01     Aberdeenshire  2024-25      3.78     7458.00  1972597.00
44     C&L01             Angus  2024-25      4.84     3767.00   777642.00
59     C&L01     Argyll & Bute  2024-25      3.23     2017.00   624398.00
74     C&L01  Clackmannanshire  2024-25      2.43      389.00   160225.00
...      ...               ...      ...       ...         ...         ...
41331  SW03a          Scotland  2024-25      0.62         nan         nan
41367   SW05          Scotland  2021-22    653.36   949083.60    27935.00
41368   SW05          Scotland  2022-23    685.19  1007719.00    28283.00
41369   SW05          Scotland  2023-24    708.86  1060595.08    28773.00
41370   SW05          Scotland  2024-25    731.96  1094847.74    28765.00

[1326 rows x 6 columns]

In [15]:
from google.colab import files
new_set. to_excel('new_set.xlsx')
files.download('new_set.xlsx')

In [16]:
df1.merge(df2, on=['Code','LocalAuthority','Year'], suffixes=['_old','_new']).drop_duplicates(keep= False) # just a test no need to run this!!!

,Code,LocalAuthority,Year,Indicator_old,Numerator_old,Denominator_old,Indicator_new,Numerator_new,Denominator_new
0,C&L01,Aberdeen City,2010-11,0.33,637.00,1922292.00,0.33,637.00,1922292.00
1,C&L01,Aberdeen City,2011-12,0.76,1554.00,2045051.00,0.76,1554.00,2045051.00
2,C&L01,Aberdeen City,2012-13,3.64,7883.00,2163756.00,3.64,7883.00,2163756.00
3,C&L01,Aberdeen City,2013-14,3.48,7726.00,2222588.00,3.48,7726.00,2222588.00
4,C&L01,Aberdeen City,2014-15,3.02,7517.00,2487138.00,3.02,7517.00,2487138.00
...,...,...,...,...,...,...,...,...,...
40379,SW07,Scotland,2020-21,0.82,nan,nan,0.82,nan,nan
40380,SW07,Scotland,2021-22,0.76,nan,nan,0.76,nan,nan
40381,SW07,Scotland,2022-23,0.75,nan,nan,0.75,nan,nan
40382,SW07,Scotland,2023-24,0.77,nan,nan,0.77,nan,nan
40383,SW07,Scotland,2024-25,0.82,nan,nan,0.82,nan,nan

In [17]:
def dataframe_difference(df1, df2, which=None):
    """Find rows which are different between two DataFrames."""
    comparison_df = df1.merge(
        df2,
        indicator=True,
        how='outer'
    )
    if which is None:
        diff_df = comparison_df[comparison_df['_merge'] != 'both']  # Identify data changes/updates
    else:
        diff_df = comparison_df[comparison_df['_merge'] == which]
    return diff_df

In [18]:
def getColChangedName(row):
    colsChanged = []
    for c in df1.columns.values:
        if row[c+"_diff"] == True:
            colsChanged.append(c)
    return ", ".join(colsChanged)

In [19]:
df1 = old_df.set_index(['Code', 'LocalAuthority', 'Year'])
df2 = new_set.set_index(['Code','LocalAuthority', 'Year'])

diffs = df1.merge(df2, left_index=True, right_index=True, suffixes=('_old', '_new'))

diff_cols = [c+"_diff" for c in df1.columns.values]

for c in df1.columns.values:
    diffs[c+"_diff"] = diffs[c+"_old"] != diffs[c+"_new"]

diffs["Record_Changed"] = diffs[diff_cols].sum(axis=1)/len(diff_cols) > 0


diffs = diffs[diffs["Record_Changed"] == 1]
diffs["Cols_Changed"] = diffs.apply(lambda row: getColChangedName(row), axis=1)

diffs

                             Indicator_old Numerator_old Denominator_old  \
Code  LocalAuthority Year
C&L02 Eilean Siar    2023-24          1.60        686.00       427894.00
C&L03 North Ayrshire 2018-19          0.39         74.00       189477.00
                     2019-20          0.40         49.00       123584.00
                     2020-21          0.49         87.00       178506.00
                     2021-22          0.34         45.00       134205.00
...                                    ...           ...             ...
SW03a Scotland       2022-23          0.62           nan             nan
                     2023-24          0.63           nan             nan
SW05  Scotland       2021-22        661.77     949083.60        27580.00
                     2022-23        690.14    1007719.00        28080.00
                     2023-24        723.01    1060595.08        28210.00

                             Indicator_new Numerator_new Denominator_new  \
Code  LocalAuthority Year
C&L02 Eilean Siar    2023-24          5.95        686.00       115332.00
C&L03 North Ayrshire 2018-19          0.65         74.00       114074.00
                     2019-20          0.42         49.00       116896.00
                     2020-21          0.52         87.00       167309.00
                     2021-22          0.43         45.00       104526.00
...                                    ...           ...             ...
SW03a Scotland       2022-23          0.61           nan             nan
                     2023-24          0.62           nan             nan
SW05  Scotland       2021-22        653.36     949083.60        27935.00
                     2022-23        685.19    1007719.00        28283.00
                     2023-24        708.86    1060595.08        28773.00

                              Indicator_diff  Numerator_diff  \
Code  LocalAuthority Year
C&L02 Eilean Siar    2023-24            True           False
C&L03 North Ayrshire 2018-19            True           False
                     2019-20            True           False
                     2020-21            True           False
                     2021-22            True           False
...                                      ...             ...
SW03a Scotland       2022-23            True           False
                     2023-24            True           False
SW05  Scotland       2021-22            True           False
                     2022-23            True           False
                     2023-24            True           False

                              Denominator_diff  Record_Changed  \
Code  LocalAuthority Year
C&L02 Eilean Siar    2023-24              True            True
C&L03 North Ayrshire 2018-19              True            True
                     2019-20              True            True
                     2020-21              True            True
                     2021-22              True            True
...                                        ...             ...
SW03a Scotland       2022-23             False            True
                     2023-24             False            True
SW05  Scotland       2021-22              True            True
                     2022-23              True            True
                     2023-24              True            True

                                        Cols_Changed
Code  LocalAuthority Year
C&L02 Eilean Siar    2023-24  Indicator, Denominator
C&L03 North Ayrshire 2018-19  Indicator, Denominator
                     2019-20  Indicator, Denominator
                     2020-21  Indicator, Denominator
                     2021-22  Indicator, Denominator
...                                              ...
SW03a Scotland       2022-23               Indicator
                     2023-24               Indicator
SW05  Scotland       2021-22  Indicator, Denominator
                     2022-23  Indicator, Denominator
                     2023-24  Indicator, Denominator

[310 rows x 11 columns]

In [20]:
from google.colab import files
diffs. to_excel('diffs.xlsx')
files.download('diffs.xlsx')

In [21]:
old_df

        Code LocalAuthority     Year Indicator Numerator Denominator
0      C&L01  Aberdeen City  2010-11      0.33    637.00  1922292.00
1      C&L01  Aberdeen City  2011-12      0.76   1554.00  2045051.00
2      C&L01  Aberdeen City  2012-13      3.64   7883.00  2163756.00
3      C&L01  Aberdeen City  2013-14      3.48   7726.00  2222588.00
4      C&L01  Aberdeen City  2014-15      3.02   7517.00  2487138.00
...      ...            ...      ...       ...       ...         ...
40406   SW07       Scotland  2020-21      0.82       nan         nan
40407   SW07       Scotland  2021-22      0.76       nan         nan
40408   SW07       Scotland  2022-23      0.75       nan         nan
40409   SW07       Scotland  2023-24      0.77       nan         nan
40410   SW07       Scotland  2024-25      0.82       nan         nan

[40411 rows x 6 columns]

In [22]:
temp = new_df.rename({'Year': 'Year_new'}, axis=1)
temp

        Code LocalAuthority Year_new Indicator Numerator Denominator
0      C&L01  Aberdeen City  2010-11      0.33    637.00  1922292.00
1      C&L01  Aberdeen City  2011-12      0.76   1554.00  2045051.00
2      C&L01  Aberdeen City  2012-13      3.64   7883.00  2163756.00
3      C&L01  Aberdeen City  2013-14      3.48   7726.00  2222588.00
4      C&L01  Aberdeen City  2014-15      3.02   7517.00  2487138.00
...      ...            ...      ...       ...       ...         ...
41395   SW07       Scotland  2020-21      0.82       nan         nan
41396   SW07       Scotland  2021-22      0.76       nan         nan
41397   SW07       Scotland  2022-23      0.75       nan         nan
41398   SW07       Scotland  2023-24      0.77       nan         nan
41399   SW07       Scotland  2024-25      0.82       nan         nan

[41400 rows x 6 columns]

In [23]:
old_df

        Code LocalAuthority     Year Indicator Numerator Denominator
0      C&L01  Aberdeen City  2010-11      0.33    637.00  1922292.00
1      C&L01  Aberdeen City  2011-12      0.76   1554.00  2045051.00
2      C&L01  Aberdeen City  2012-13      3.64   7883.00  2163756.00
3      C&L01  Aberdeen City  2013-14      3.48   7726.00  2222588.00
4      C&L01  Aberdeen City  2014-15      3.02   7517.00  2487138.00
...      ...            ...      ...       ...       ...         ...
40406   SW07       Scotland  2020-21      0.82       nan         nan
40407   SW07       Scotland  2021-22      0.76       nan         nan
40408   SW07       Scotland  2022-23      0.75       nan         nan
40409   SW07       Scotland  2023-24      0.77       nan         nan
40410   SW07       Scotland  2024-25      0.82       nan         nan

[40411 rows x 6 columns]

In [24]:
#find rows with added data from new year
temp = new_df.rename({'Year': 'Year_new'}, axis=1)
#merged = temp.merge(old_df, how='left', left_on=['LocalAuthority','Code','Year_new'], right_on=['LocalAuthority','Code','Year'])
merged = temp.merge(old_df, how='left', left_on=['LocalAuthority','Year_new'], right_on=['LocalAuthority','Year'],indicator='Match')
new_year_df = np.where(merged['Year'].isnull())[0]
new_year_df

array([], dtype=int64)

# create a new data frame with just the new year's data

In [25]:
#new year added data
new_Data = pd.concat([old_df,new_df]).drop_duplicates(subset=["Code", "LocalAuthority", 'Year'], keep=False)

In [26]:
new_Data

           Code    LocalAuthority     Year Indicator    Numerator  Denominator
34858     HSN03     Aberdeen City  2024-26       nan          nan       473.00
34871     HSN03     Aberdeenshire  2024-26       nan          nan       481.00
34884     HSN03             Angus  2024-26       nan          nan       -42.00
34897     HSN03  Clackmannanshire  2024-26       nan          nan       110.00
34910     HSN03       Dundee City  2024-26       nan          nan      -259.00
...         ...               ...      ...       ...          ...          ...
41231  FINSUS05          Scotland  2024-25      1.00  16128100.00  16110287.00
41301      SW01          Scotland  2024-25     32.54    866869.00  26639597.52
41316      SW02          Scotland  2024-25      0.09    456553.71   4844069.19
41331     SW03a          Scotland  2024-25      0.62          nan          nan
41370      SW05          Scotland  2024-25    731.96   1094847.74     28765.00

[1043 rows x 6 columns]

In [27]:
from google.colab import files
new_Data. to_excel('new_Data.xlsx')
files.download('new_Data.xlsx')

#Use diff and new_Data to get the Change log