<a href="https://colab.research.google.com/github/LGBFBenchmarking/ChangeLogMaker/blob/main/Automate_differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Test code for automated output file

#Load files

##new_df is new data including new year's data
##diff_df has old data (no changes or new data for the new year)

In [285]:
import pandas as pd
import numpy as np

def get_data(url): # this function gets data stored as csv file from a given url
  df = pd.read_csv(url)
  return df

In [286]:
url_old = "https://raw.githubusercontent.com/LGBFBenchmarking/ChangeLogMaker/refs/heads/main/LGBF_Data_Apr26.csv"
url_new = "https://raw.githubusercontent.com/LGBFBenchmarking/ChangeLogMaker/refs/heads/main/LGBF_Data_May26.csv"
old_df = get_data(url_old)
new_df = get_data(url_new)

In [287]:
new_df['Indicator'] = new_df['Indicator'].map("{:.2f}".format)
new_df['Numerator'] = new_df['Numerator'].map('{:.2f}'.format)
new_df['Denominator'] = new_df['Denominator'].map('{:.2f}'.format)

In [288]:
old_df['Indicator'] = old_df['Indicator'].map('{:.2f}'.format)
old_df['Numerator'] = old_df['Numerator'].map('{:.2f}'.format)
old_df['Denominator'] = old_df['Denominator'].map('{:.2f}'.format)

In [289]:
old_df = old_df.round(4)
new_df = new_df.round(4)

In [290]:
df1 = old_df
df2 = new_df

In [291]:
new_set = df2[~df2.astype(str).apply(tuple, 1).isin(df1.astype(str).apply(tuple, 1))]

In [293]:
out = pd.merge(old_df, new_df, on=['Code', 'LocalAuthority', 'Year'], how='outer',
               suffixes=('_old', '_new')).set_index(['Code', 'LocalAuthority', 'Year'])

out.columns = pd.MultiIndex.from_tuples(out.columns.str.split('_').map(tuple)).swaplevel()
out

                                   old                             new  \
                             Indicator Numerator Denominator Indicator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11      0.33    637.00  1922292.00      0.33
                     2011-12      0.76   1554.00  2045051.00      0.76
                     2012-13      3.64   7883.00  2163756.00      3.64
                     2013-14      3.48   7726.00  2222588.00      3.48
                     2014-15      3.02   7517.00  2487138.00      3.02
...                                ...       ...         ...       ...
SW08  West Lothian   2020-21    369.62   4692.00    12694.00    369.62
                     2021-22    439.50   5750.00    13083.00    439.50
                     2022-23    639.84   8856.00    13841.00    639.84
                     2023-24    809.85  11742.00    14499.00    809.85
                     2024-25    960.18  14466.00    15066.00    960.18


                             Numerator Denominator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11    637.00  1922292.00
                     2011-12   1554.00  2045051.00
                     2012-13   7883.00  2163756.00
                     2013-14   7726.00  2222588.00
                     2014-15   7517.00  2487138.00
...                                ...         ...
SW08  West Lothian   2020-21   4692.00    12694.00
                     2021-22   5750.00    13083.00
                     2022-23   8856.00    13841.00
                     2023-24  11742.00    14499.00
                     2024-25  14466.00    15066.00

[44906 rows x 6 columns]

In [294]:
out = out.drop_duplicates(keep=False)
out

                                   old                             new  \
                             Indicator Numerator Denominator Indicator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11      0.33    637.00  1922292.00      0.33
                     2011-12      0.76   1554.00  2045051.00      0.76
                     2012-13      3.64   7883.00  2163756.00      3.64
                     2013-14      3.48   7726.00  2222588.00      3.48
                     2014-15      3.02   7517.00  2487138.00      3.02
...                                ...       ...         ...       ...
SW08  West Lothian   2020-21    369.62   4692.00    12694.00    369.62
                     2021-22    439.50   5750.00    13083.00    439.50
                     2022-23    639.84   8856.00    13841.00    639.84
                     2023-24    809.85  11742.00    14499.00    809.85
                     2024-25    960.18  14466.00    15066.00    960.18


                             Numerator Denominator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11    637.00  1922292.00
                     2011-12   1554.00  2045051.00
                     2012-13   7883.00  2163756.00
                     2013-14   7726.00  2222588.00
                     2014-15   7517.00  2487138.00
...                                ...         ...
SW08  West Lothian   2020-21   4692.00    12694.00
                     2021-22   5750.00    13083.00
                     2022-23   8856.00    13841.00
                     2023-24  11742.00    14499.00
                     2024-25  14466.00    15066.00

[23709 rows x 6 columns]

In [295]:
new_set

        Code       LocalAuthority     Year Indicator Numerator Denominator
14855  CHN23     Clackmannanshire  2021-22      0.15       nan         nan
14856  CHN23     Clackmannanshire  2022-23      0.17       nan         nan
14857  CHN23     Clackmannanshire  2023-24      0.16       nan         nan
14858  CHN23     Clackmannanshire  2024-25      0.23       nan         nan
14870  CHN23  Dumfries & Galloway  2021-22      0.19       nan         nan
...      ...                  ...      ...       ...       ...         ...
44827  SW04b             Scotland  2025-26      0.72       nan         nan
44834  SW04c             Scotland  2025-26      0.74       nan         nan
44841  SW04d             Scotland  2025-26      0.64       nan         nan
44848  SW04e             Scotland  2025-26      0.32       nan         nan
44893   SW07             Scotland  2025-26      0.83       nan         nan

[341 rows x 6 columns]

In [296]:
df1.merge(df2, on=['Code','LocalAuthority','Year'], suffixes=['_old','_new']).drop_duplicates(keep= False) # just a test no need to run this!!!

,Code,LocalAuthority,Year,Indicator_old,Numerator_old,Denominator_old,Indicator_new,Numerator_new,Denominator_new
0,C&L01,Aberdeen City,2010-11,0.33,637.00,1922292.00,0.33,637.00,1922292.00
1,C&L01,Aberdeen City,2011-12,0.76,1554.00,2045051.00,0.76,1554.00,2045051.00
2,C&L01,Aberdeen City,2012-13,3.64,7883.00,2163756.00,3.64,7883.00,2163756.00
3,C&L01,Aberdeen City,2013-14,3.48,7726.00,2222588.00,3.48,7726.00,2222588.00
4,C&L01,Aberdeen City,2014-15,3.02,7517.00,2487138.00,3.02,7517.00,2487138.00
...,...,...,...,...,...,...,...,...,...
44671,SW08,Scotland,2020-21,485.45,227524.00,468682.00,485.45,227524.00,468682.00
44672,SW08,Scotland,2021-22,749.73,357719.00,477131.00,749.73,357719.00,477131.00
44673,SW08,Scotland,2022-23,882.88,439596.00,497909.00,882.88,439596.00,497909.00
44674,SW08,Scotland,2023-24,841.47,431429.00,512706.00,841.47,431429.00,512706.00
44675,SW08,Scotland,2024-25,898.95,474153.00,527454.00,898.95,474153.00,527454.00

In [297]:
def dataframe_difference(df1, df2, which=None):
    """Find rows which are different between two DataFrames."""
    comparison_df = df1.merge(
        df2,
        indicator=True,
        how='outer'
    )
    if which is None:
        diff_df = comparison_df[comparison_df['_merge'] != 'both']  # Identify data changes/updates
    else:
        diff_df = comparison_df[comparison_df['_merge'] == which]
    return diff_df

In [298]:
def getColChangedName(row):
    colsChanged = []
    for c in df1.columns.values:
        if row[c+"_diff"] == True:
            colsChanged.append(c)
    return ", ".join(colsChanged)

In [335]:
df1 = old_df.set_index(['Code', 'LocalAuthority', 'Year'])
df2 = new_set.set_index(['Code','LocalAuthority', 'Year'])

diffs = df1.merge(df2, left_index=True, right_index=True, suffixes=('_old', '_new'))

diff_cols = [c+"_diff" for c in df1.columns.values]
diffs

                                     Indicator_old Numerator_old  \
Code     LocalAuthority      Year
CHN23    Clackmannanshire    2021-22          0.19           nan
                             2022-23          0.20           nan
                             2023-24          0.20           nan
                             2024-25          0.20           nan
         Dumfries & Galloway 2021-22          0.15           nan
...                                            ...           ...
C&L02    Scotland            2021-22          2.91      89241.00
CHN08b   Scotland            2023-24        474.68     259617.00
CHN23    Scotland            2024-25          0.17           nan
ECON05   Scotland            2024-25         13.43       7449.00
FINSUS05 Scotland            2019-20          0.99   12612014.57

                                     Denominator_old Indicator_new  \
Code     LocalAuthority      Year
CHN23    Clackmannanshire    2021-22             nan          0.15
                             2022-23             nan          0.17
                             2023-24             nan          0.16
                             2024-25             nan          0.23
         Dumfries & Galloway 2021-22             nan          0.19
...                                              ...           ...
C&L02    Scotland            2021-22     30702692.00           nan
CHN08b   Scotland            2023-24        10518.00        477.58
CHN23    Scotland            2024-25             nan          0.16
ECON05   Scotland            2024-25      5546900.00         12.26
FINSUS05 Scotland            2019-20     12694498.43           nan

                                     Numerator_new Denominator_new
Code     LocalAuthority      Year
CHN23    Clackmannanshire    2021-22           nan             nan
                             2022-23           nan             nan
                             2023-24           nan             nan
                             2024-25           nan             nan
         Dumfries & Galloway 2021-22           nan             nan
...                                            ...             ...
C&L02    Scotland            2021-22           nan     30702692.00
CHN08b   Scotland            2023-24     259617.00        10454.00
CHN23    Scotland            2024-25           nan             nan
ECON05   Scotland            2024-25       6800.00      5546900.00
FINSUS05 Scotland            2019-20           nan             nan

[111 rows x 6 columns]

In [149]:
#from google.colab import files
#diffs. to_excel('diffs.xlsx')
#files.download('diffs.xlsx')

In [302]:
temp = new_df.rename({'Year': 'Year_new'}, axis=1)
temp

        Code LocalAuthority Year_new Indicator  Numerator Denominator
0      C&L01  Aberdeen City  2010-11      0.33     637.00  1922292.00
1      C&L01  Aberdeen City  2011-12      0.76    1554.00  2045051.00
2      C&L01  Aberdeen City  2012-13      3.64    7883.00  2163756.00
3      C&L01  Aberdeen City  2013-14      3.48    7726.00  2222588.00
4      C&L01  Aberdeen City  2014-15      3.02    7517.00  2487138.00
...      ...            ...      ...       ...        ...         ...
44901   SW08       Scotland  2020-21    485.45  227524.00   468682.00
44902   SW08       Scotland  2021-22    749.73  357719.00   477131.00
44903   SW08       Scotland  2022-23    882.88  439596.00   497909.00
44904   SW08       Scotland  2023-24    841.47  431429.00   512706.00
44905   SW08       Scotland  2024-25    898.95  474153.00   527454.00

[44906 rows x 6 columns]

# create a new data frame with just the new year's data

In [303]:
#new year added data
new_Data = pd.concat([old_df,new_df]).drop_duplicates(subset=["Code", "LocalAuthority", 'Year'], keep=False)

In [304]:
new_Data

         Code    LocalAuthority     Year Indicator   Numerator Denominator
21799  CORP12     Aberdeen City  2025-26      0.93  2963829.00  3181784.00
21808  CORP12     Aberdeenshire  2025-26      0.78  1742066.00  2245803.00
21817  CORP12             Angus  2025-26      0.89  1042600.00  1176166.00
21826  CORP12     Argyll & Bute  2025-26      0.77  1045070.00  1348585.00
21835  CORP12  Clackmannanshire  2025-26      0.95  1100327.00  1162257.00
...       ...               ...      ...       ...         ...         ...
44827   SW04b          Scotland  2025-26      0.72         nan         nan
44834   SW04c          Scotland  2025-26      0.74         nan         nan
44841   SW04d          Scotland  2025-26      0.64         nan         nan
44848   SW04e          Scotland  2025-26      0.32         nan         nan
44893    SW07          Scotland  2025-26      0.83         nan         nan

[230 rows x 6 columns]

In [305]:
new_Data.rename(columns={'Indicator': 'Indicator new value', 'Numerator': 'Numerator new value','Denominator': 'Denominator new value'}, inplace=True)
new_Data

,Code,LocalAuthority,Year,Indicator new value,Numerator new value,Denominator new value
21799,CORP12,Aberdeen City,2025-26,0.93,2963829.00,3181784.00
21808,CORP12,Aberdeenshire,2025-26,0.78,1742066.00,2245803.00
21817,CORP12,Angus,2025-26,0.89,1042600.00,1176166.00
21826,CORP12,Argyll & Bute,2025-26,0.77,1045070.00,1348585.00
21835,CORP12,Clackmannanshire,2025-26,0.95,1100327.00,1162257.00
...,...,...,...,...,...,...
44827,SW04b,Scotland,2025-26,0.72,nan,nan
44834,SW04c,Scotland,2025-26,0.74,nan,nan
44841,SW04d,Scotland,2025-26,0.64,nan,nan
44848,SW04e,Scotland,2025-26,0.32,nan,nan
44893,SW07,Scotland,2025-26,0.83,nan,nan

#Time to create the change log
##Standardise column names

In [314]:
diffs.columns = diffs.columns.str.strip()
new_Data.columns = new_Data.columns.str.strip()

In [320]:
diffs

                                     Indicator old value Numerator old value  \
Code     LocalAuthority      Year
CHN23    Clackmannanshire    2021-22                0.19                 nan
                             2022-23                0.20                 nan
                             2023-24                0.20                 nan
                             2024-25                0.20                 nan
         Dumfries & Galloway 2021-22                0.15                 nan
...                                                  ...                 ...
C&L02    Scotland            2021-22                2.91            89241.00
CHN08b   Scotland            2023-24              474.68           259617.00
CHN23    Scotland            2024-25                0.17                 nan
ECON05   Scotland            2024-25               13.43             7449.00
FINSUS05 Scotland            2019-20                0.99         12612014.57

                                     Denominator old value  \
Code     LocalAuthority      Year
CHN23    Clackmannanshire    2021-22                   nan
                             2022-23                   nan
                             2023-24                   nan
                             2024-25                   nan
         Dumfries & Galloway 2021-22                   nan
...                                                    ...
C&L02    Scotland            2021-22           30702692.00
CHN08b   Scotland            2023-24              10518.00
CHN23    Scotland            2024-25                   nan
ECON05   Scotland            2024-25            5546900.00
FINSUS05 Scotland            2019-20           12694498.43

                                     Indicator new value Numerator new value  \
Code     LocalAuthority      Year
CHN23    Clackmannanshire    2021-22                0.15                 nan
                             2022-23                0.17                 nan
                             2023-24                0.16                 nan
                             2024-25                0.23                 nan
         Dumfries & Galloway 2021-22                0.19                 nan
...                                                  ...                 ...
C&L02    Scotland            2021-22                 nan                 nan
CHN08b   Scotland            2023-24              477.58           259617.00
CHN23    Scotland            2024-25                0.16                 nan
ECON05   Scotland            2024-25               12.26             6800.00
FINSUS05 Scotland            2019-20                 nan                 nan

                                     Denominator new value
Code     LocalAuthority      Year
CHN23    Clackmannanshire    2021-22                   nan
                             2022-23                   nan
                             2023-24                   nan
                             2024-25                   nan
         Dumfries & Galloway 2021-22                   nan
...                                                    ...
C&L02    Scotland            2021-22           30702692.00
CHN08b   Scotland            2023-24              10454.00
CHN23    Scotland            2024-25                   nan
ECON05   Scotland            2024-25            5546900.00
FINSUS05 Scotland            2019-20                   nan

[111 rows x 6 columns]

##Rename columns (diffs → final format)

In [321]:
diffs_renamed = diffs.rename(columns={'Indicator_old': 'Indicator old value','Numerator_old': 'Numerator old value', 'Denominator_old': 'Denominator old value','Indicator_new': 'Indicator new value','Numerator_new': 'Numerator new value', 'Denominator_new': 'Denominator new value'})

In [322]:
diffs_renamed

                                     Indicator old value Numerator old value  \
Code     LocalAuthority      Year
CHN23    Clackmannanshire    2021-22                0.19                 nan
                             2022-23                0.20                 nan
                             2023-24                0.20                 nan
                             2024-25                0.20                 nan
         Dumfries & Galloway 2021-22                0.15                 nan
...                                                  ...                 ...
C&L02    Scotland            2021-22                2.91            89241.00
CHN08b   Scotland            2023-24              474.68           259617.00
CHN23    Scotland            2024-25                0.17                 nan
ECON05   Scotland            2024-25               13.43             7449.00
FINSUS05 Scotland            2019-20                0.99         12612014.57

                                     Denominator old value  \
Code     LocalAuthority      Year
CHN23    Clackmannanshire    2021-22                   nan
                             2022-23                   nan
                             2023-24                   nan
                             2024-25                   nan
         Dumfries & Galloway 2021-22                   nan
...                                                    ...
C&L02    Scotland            2021-22           30702692.00
CHN08b   Scotland            2023-24              10518.00
CHN23    Scotland            2024-25                   nan
ECON05   Scotland            2024-25            5546900.00
FINSUS05 Scotland            2019-20           12694498.43

                                     Indicator new value Numerator new value  \
Code     LocalAuthority      Year
CHN23    Clackmannanshire    2021-22                0.15                 nan
                             2022-23                0.17                 nan
                             2023-24                0.16                 nan
                             2024-25                0.23                 nan
         Dumfries & Galloway 2021-22                0.19                 nan
...                                                  ...                 ...
C&L02    Scotland            2021-22                 nan                 nan
CHN08b   Scotland            2023-24              477.58           259617.00
CHN23    Scotland            2024-25                0.16                 nan
ECON05   Scotland            2024-25               12.26             6800.00
FINSUS05 Scotland            2019-20                 nan                 nan

                                     Denominator new value
Code     LocalAuthority      Year
CHN23    Clackmannanshire    2021-22                   nan
                             2022-23                   nan
                             2023-24                   nan
                             2024-25                   nan
         Dumfries & Galloway 2021-22                   nan
...                                                    ...
C&L02    Scotland            2021-22           30702692.00
CHN08b   Scotland            2023-24              10454.00
CHN23    Scotland            2024-25                   nan
ECON05   Scotland            2024-25            5546900.00
FINSUS05 Scotland            2019-20                   nan

[111 rows x 6 columns]

In [341]:
new_data_renamed = new_Data.rename(columns={ "Code": "Indicator Code"})

In [336]:
# Add missing OLD columns (since these are new entries)
new_Data["Indicator old value"] = pd.NA
new_Data["Numerator old value"] = pd.NA
new_Data["Denominator old value"] = pd.NA

In [337]:
new_Data

,Code,LocalAuthority,Year,Indicator new value,Numerator new value,Denominator new value,Indicator old value,Numerator old value,Denominator old value
21799,CORP12,Aberdeen City,2025-26,0.93,2963829.00,3181784.00,<NA>,<NA>,<NA>
21808,CORP12,Aberdeenshire,2025-26,0.78,1742066.00,2245803.00,<NA>,<NA>,<NA>
21817,CORP12,Angus,2025-26,0.89,1042600.00,1176166.00,<NA>,<NA>,<NA>
21826,CORP12,Argyll & Bute,2025-26,0.77,1045070.00,1348585.00,<NA>,<NA>,<NA>
21835,CORP12,Clackmannanshire,2025-26,0.95,1100327.00,1162257.00,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...
44827,SW04b,Scotland,2025-26,0.72,nan,nan,<NA>,<NA>,<NA>
44834,SW04c,Scotland,2025-26,0.74,nan,nan,<NA>,<NA>,<NA>
44841,SW04d,Scotland,2025-26,0.64,nan,nan,<NA>,<NA>,<NA>
44848,SW04e,Scotland,2025-26,0.32,nan,nan,<NA>,<NA>,<NA>
44893,SW07,Scotland,2025-26,0.83,nan,nan,<NA>,<NA>,<NA>

In [338]:
key_cols = ["Code", "LocalAuthority", "Year"]

In [345]:
diffs_renamed_temp = diffs_renamed.reset_index()
# Create key to compare using original 'Code' column
diffs_keys = diffs_renamed_temp[key_cols].astype(str).agg("|".join, axis=1)
new_keys = new_Data[key_cols].astype(str).agg("|".join, axis=1)

# Ensure 'Code' column is renamed to 'Indicator Code' for consistent concatenation
diffs_renamed_temp = diffs_renamed_temp.rename(columns={"Code": "Indicator Code"})

In [346]:
new_rows_mask = ~new_keys.isin(diffs_keys)
new_rows = new_data_renamed[new_rows_mask].copy()

# Rename new_data columns to match changelog
new_rows = new_rows.rename(columns={
    "Indicator new value": "Indicator new value",
    "Numerator new value": "Numerator new value",
    "Denominator new value": "Denominator new value"
})

In [347]:
# Keep only required columns

new_rows = new_rows[[
    "Indicator Code",
    "LocalAuthority",
    "Year",
    "Indicator old value",
    "Numerator old value",
    "Denominator old value",
    "Indicator new value",
    "Numerator new value",
    "Denominator new value"
]]

In [357]:
new_rows

,Indicator Code,LocalAuthority,Year,Indicator old value,Numerator old value,Denominator old value,Indicator new value,Numerator new value,Denominator new value
21799,CORP12,Aberdeen City,2025-26,<NA>,<NA>,<NA>,0.93,2963829.00,3181784.00
21808,CORP12,Aberdeenshire,2025-26,<NA>,<NA>,<NA>,0.78,1742066.00,2245803.00
21817,CORP12,Angus,2025-26,<NA>,<NA>,<NA>,0.89,1042600.00,1176166.00
21826,CORP12,Argyll & Bute,2025-26,<NA>,<NA>,<NA>,0.77,1045070.00,1348585.00
21835,CORP12,Clackmannanshire,2025-26,<NA>,<NA>,<NA>,0.95,1100327.00,1162257.00
...,...,...,...,...,...,...,...,...,...
44827,SW04b,Scotland,2025-26,<NA>,<NA>,<NA>,0.72,nan,nan
44834,SW04c,Scotland,2025-26,<NA>,<NA>,<NA>,0.74,nan,nan
44841,SW04d,Scotland,2025-26,<NA>,<NA>,<NA>,0.64,nan,nan
44848,SW04e,Scotland,2025-26,<NA>,<NA>,<NA>,0.32,nan,nan
44893,SW07,Scotland,2025-26,<NA>,<NA>,<NA>,0.83,nan,nan

In [358]:
target_cols = [
    "Indicator Code",
    "LocalAuthority",
    "Year",
    "Indicator old value",
    "Numerator old value",
    "Denominator old value",
    "Indicator new value",
    "Numerator new value",
    "Denominator new value"
]

# Ensure diffs_renamed_temp has the correct columns and order
diffs_renamed_temp_aligned = diffs_renamed_temp[target_cols]

# Ensure new_data_renamed has the correct columns and order
new_data_renamed_aligned = new_data_renamed[target_cols]

changelog = pd.concat([diffs_renamed_temp_aligned, new_data_renamed_aligned], ignore_index=True)

In [359]:
changelog

,Code,LocalAuthority,Year,Indicator old value,Numerator old value,Denominator old value,Indicator new value,Numerator new value,Denominator new value,Indicator Code
0,CHN23,Clackmannanshire,2021-22,0.19,nan,nan,0.15,nan,nan,NaN
1,CHN23,Clackmannanshire,2022-23,0.20,nan,nan,0.17,nan,nan,NaN
2,CHN23,Clackmannanshire,2023-24,0.20,nan,nan,0.16,nan,nan,NaN
3,CHN23,Clackmannanshire,2024-25,0.20,nan,nan,0.23,nan,nan,NaN
4,CHN23,Dumfries & Galloway,2021-22,0.15,nan,nan,0.19,nan,nan,NaN
...,...,...,...,...,...,...,...,...,...,...
336,NaN,Scotland,2025-26,NaN,NaN,NaN,0.72,nan,nan,SW04b
337,NaN,Scotland,2025-26,NaN,NaN,NaN,0.74,nan,nan,SW04c
338,NaN,Scotland,2025-26,NaN,NaN,NaN,0.64,nan,nan,SW04d
339,NaN,Scotland,2025-26,NaN,NaN,NaN,0.32,nan,nan,SW04e
340,NaN,Scotland,2025-26,NaN,NaN,NaN,0.83,nan,nan,SW07

In [355]:
from google.colab import files
changelog. to_excel('changelog.xlsx')
files.download('changelog.xlsx')

AttributeError: 'NoneType' object has no attribute 'to_excel'