<a href="https://colab.research.google.com/github/LGBFBenchmarking/ChangeLogMaker/blob/main/Automate_differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Test code for automated output file

#Load files

##new_df is new data including new year's data
##diff_df has old data (no changes or new data for the new year)

In [1]:
import pandas as pd
import numpy as np

def get_data(url): # this function gets data stored as csv file from a given url
  df = pd.read_csv(url)
  return df

In [2]:
url_old = "https://raw.githubusercontent.com/LGBFBenchmarking/ChangeLogMaker/refs/heads/main/LGBF_Data_May26.csv"
url_new = "https://raw.githubusercontent.com/LGBFBenchmarking/ChangeLogMaker/refs/heads/main/LGBF_data_Jun26.csv"
old_df = get_data(url_old)
new_df = get_data(url_new)

In [3]:
new_df['Indicator'] = new_df['Indicator'].map("{:.2f}".format)
new_df['Numerator'] = new_df['Numerator'].map('{:.2f}'.format)
new_df['Denominator'] = new_df['Denominator'].map('{:.2f}'.format)

In [4]:
old_df['Indicator'] = old_df['Indicator'].map('{:.2f}'.format)
old_df['Numerator'] = old_df['Numerator'].map('{:.2f}'.format)
old_df['Denominator'] = old_df['Denominator'].map('{:.2f}'.format)

In [5]:
old_df = old_df.round(4)
new_df = new_df.round(4)

In [6]:
df1 = old_df
df2 = new_df

In [7]:
new_set = df2[~df2.astype(str).apply(tuple, 1).isin(df1.astype(str).apply(tuple, 1))]

In [8]:
out = pd.merge(old_df, new_df, on=['Code', 'LocalAuthority', 'Year'], how='outer',
               suffixes=('_old', '_new')).set_index(['Code', 'LocalAuthority', 'Year'])

out.columns = pd.MultiIndex.from_tuples(out.columns.str.split('_').map(tuple)).swaplevel()
out

                                   old                             new  \
                             Indicator Numerator Denominator Indicator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11      0.33    637.00  1922292.00      0.33
                     2011-12      0.76   1554.00  2045051.00      0.76
                     2012-13      3.64   7883.00  2163756.00      3.64
                     2013-14      3.48   7726.00  2222588.00      3.48
                     2014-15      3.02   7517.00  2487138.00      3.02
...                                ...       ...         ...       ...
SW08  West Lothian   2020-21    369.62   4692.00    12694.00    369.62
                     2021-22    439.50   5750.00    13083.00    439.50
                     2022-23    639.84   8856.00    13841.00    639.84
                     2023-24    809.85  11742.00    14499.00    809.85
                     2024-25    960.18  14466.00    15066.00    960.18


                             Numerator Denominator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11    637.00  1922292.00
                     2011-12   1554.00  2045051.00
                     2012-13   7883.00  2163756.00
                     2013-14   7726.00  2222588.00
                     2014-15   7517.00  2487138.00
...                                ...         ...
SW08  West Lothian   2020-21   4692.00    12694.00
                     2021-22   5750.00    13083.00
                     2022-23   8856.00    13841.00
                     2023-24  11742.00    14499.00
                     2024-25  14466.00    15066.00

[45166 rows x 6 columns]

In [9]:
out = out.drop_duplicates(keep=False)
out

                                   old                             new  \
                             Indicator Numerator Denominator Indicator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11      0.33    637.00  1922292.00      0.33
                     2011-12      0.76   1554.00  2045051.00      0.76
                     2012-13      3.64   7883.00  2163756.00      3.64
                     2013-14      3.48   7726.00  2222588.00      3.48
                     2014-15      3.02   7517.00  2487138.00      3.02
...                                ...       ...         ...       ...
SW08  West Lothian   2020-21    369.62   4692.00    12694.00    369.62
                     2021-22    439.50   5750.00    13083.00    439.50
                     2022-23    639.84   8856.00    13841.00    639.84
                     2023-24    809.85  11742.00    14499.00    809.85
                     2024-25    960.18  14466.00    15066.00    960.18


                             Numerator Denominator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11    637.00  1922292.00
                     2011-12   1554.00  2045051.00
                     2012-13   7883.00  2163756.00
                     2013-14   7726.00  2222588.00
                     2014-15   7517.00  2487138.00
...                                ...         ...
SW08  West Lothian   2020-21   4692.00    12694.00
                     2021-22   5750.00    13083.00
                     2022-23   8856.00    13841.00
                     2023-24  11742.00    14499.00
                     2024-25  14466.00    15066.00

[24486 rows x 6 columns]

In [10]:
new_set

         Code LocalAuthority     Year Indicator Numerator Denominator
489     C&L02  Aberdeen City  2019-20      2.17   3764.00  1736063.00
490     C&L02  Aberdeen City  2020-21     10.74   3225.00   300291.00
491     C&L02  Aberdeen City  2021-22      2.45   3300.00  1347180.00
504     C&L02  Aberdeenshire  2019-20      1.91   3818.00  2003318.00
505     C&L02  Aberdeenshire  2020-21      3.36   3783.00  1125625.00
...       ...            ...      ...       ...       ...         ...
44563  ECON04       Scotland  2024-25      0.31       nan         nan
44775  ENV04b       Scotland  2025-26      0.30       nan         nan
44791  ENV04c       Scotland  2025-26      0.33       nan         nan
44807  ENV04d       Scotland  2025-26      0.33       nan         nan
44823  ENV04e       Scotland  2025-26      0.36       nan         nan

[1254 rows x 6 columns]

In [11]:
df1.merge(df2, on=['Code','LocalAuthority','Year'], suffixes=['_old','_new']).drop_duplicates(keep= False) # just a test no need to run this!!!

,Code,LocalAuthority,Year,Indicator_old,Numerator_old,Denominator_old,Indicator_new,Numerator_new,Denominator_new
0,C&L01,Aberdeen City,2010-11,0.33,637.00,1922292.00,0.33,637.00,1922292.00
1,C&L01,Aberdeen City,2011-12,0.76,1554.00,2045051.00,0.76,1554.00,2045051.00
2,C&L01,Aberdeen City,2012-13,3.64,7883.00,2163756.00,3.64,7883.00,2163756.00
3,C&L01,Aberdeen City,2013-14,3.48,7726.00,2222588.00,3.48,7726.00,2222588.00
4,C&L01,Aberdeen City,2014-15,3.02,7517.00,2487138.00,3.02,7517.00,2487138.00
...,...,...,...,...,...,...,...,...,...
44901,SW08,Scotland,2020-21,485.45,227524.00,468682.00,485.45,227524.00,468682.00
44902,SW08,Scotland,2021-22,749.73,357719.00,477131.00,749.73,357719.00,477131.00
44903,SW08,Scotland,2022-23,882.88,439596.00,497909.00,882.88,439596.00,497909.00
44904,SW08,Scotland,2023-24,841.47,431429.00,512706.00,841.47,431429.00,512706.00
44905,SW08,Scotland,2024-25,898.95,474153.00,527454.00,898.95,474153.00,527454.00

In [12]:
def dataframe_difference(df1, df2, which=None):
    """Find rows which are different between two DataFrames."""
    comparison_df = df1.merge(
        df2,
        indicator=True,
        how='outer'
    )
    if which is None:
        diff_df = comparison_df[comparison_df['_merge'] != 'both']  # Identify data changes/updates
    else:
        diff_df = comparison_df[comparison_df['_merge'] == which]
    return diff_df

In [13]:
def getColChangedName(row):
    colsChanged = []
    for c in df1.columns.values:
        if row[c+"_diff"] == True:
            colsChanged.append(c)
    return ", ".join(colsChanged)

In [14]:
df1 = old_df.set_index(['Code', 'LocalAuthority', 'Year'])
df2 = new_set.set_index(['Code','LocalAuthority', 'Year'])

diffs = df1.merge(df2, left_index=True, right_index=True, suffixes=('_old', '_new'))

diff_cols = [c+"_diff" for c in df1.columns.values]
diffs

                              Indicator_old Numerator_old Denominator_old  \
Code   LocalAuthority Year
C&L02  Aberdeen City  2019-20           nan           nan      1736063.00
                      2020-21           nan           nan       300291.00
                      2021-22           nan           nan      1347180.00
       Aberdeenshire  2019-20           nan           nan      2003318.00
                      2020-21           nan           nan      1125625.00
...                                     ...           ...             ...
CLIM02 Scotland       2020-21          4.17           nan             nan
                      2021-22          4.56           nan             nan
                      2023-24          4.04           nan             nan
ECON04 Scotland       2023-24          0.30           nan             nan
                      2024-25          0.32           nan             nan

                              Indicator_new Numerator_new Denominator_new
Code   LocalAuthority Year
C&L02  Aberdeen City  2019-20          2.17       3764.00      1736063.00
                      2020-21         10.74       3225.00       300291.00
                      2021-22          2.45       3300.00      1347180.00
       Aberdeenshire  2019-20          1.91       3818.00      2003318.00
                      2020-21          3.36       3783.00      1125625.00
...                                     ...           ...             ...
CLIM02 Scotland       2020-21          4.18           nan             nan
                      2021-22          4.58           nan             nan
                      2023-24          4.06           nan             nan
ECON04 Scotland       2023-24          0.31           nan             nan
                      2024-25          0.31           nan             nan

[994 rows x 6 columns]

In [15]:
#from google.colab import files
#diffs. to_excel('diffs.xlsx')
#files.download('diffs.xlsx')

In [16]:
temp = new_df.rename({'Year': 'Year_new'}, axis=1)
temp

        Code LocalAuthority Year_new Indicator  Numerator Denominator
0      C&L01  Aberdeen City  2010-11      0.33     637.00  1922292.00
1      C&L01  Aberdeen City  2011-12      0.76    1554.00  2045051.00
2      C&L01  Aberdeen City  2012-13      3.64    7883.00  2163756.00
3      C&L01  Aberdeen City  2013-14      3.48    7726.00  2222588.00
4      C&L01  Aberdeen City  2014-15      3.02    7517.00  2487138.00
...      ...            ...      ...       ...        ...         ...
45161   SW08       Scotland  2020-21    485.45  227524.00   468682.00
45162   SW08       Scotland  2021-22    749.73  357719.00   477131.00
45163   SW08       Scotland  2022-23    882.88  439596.00   497909.00
45164   SW08       Scotland  2023-24    841.47  431429.00   512706.00
45165   SW08       Scotland  2024-25    898.95  474153.00   527454.00

[45166 rows x 6 columns]

# create a new data frame with just the new year's data

In [17]:
#new year added data
new_Data = pd.concat([old_df,new_df]).drop_duplicates(subset=["Code", "LocalAuthority", 'Year'], keep=False)

In [18]:
new_Data

         Code    LocalAuthority     Year Indicator Numerator Denominator
13340  CHN19b     Aberdeen City  2024-25      0.89       nan         nan
13349  CHN19b     Aberdeenshire  2024-25      0.85       nan         nan
13358  CHN19b             Angus  2024-25      0.86       nan         nan
13367  CHN19b     Argyll & Bute  2024-25      0.85       nan         nan
13376  CHN19b  Clackmannanshire  2024-25      0.89       nan         nan
...       ...               ...      ...       ...       ...         ...
44303  CLIM02          Scotland  2024-25      3.86       nan         nan
44775  ENV04b          Scotland  2025-26      0.30       nan         nan
44791  ENV04c          Scotland  2025-26      0.33       nan         nan
44807  ENV04d          Scotland  2025-26      0.33       nan         nan
44823  ENV04e          Scotland  2025-26      0.36       nan         nan

[260 rows x 6 columns]

In [19]:
new_Data.rename(columns={'Indicator': 'Indicator new value', 'Numerator': 'Numerator new value','Denominator': 'Denominator new value'}, inplace=True)
new_Data

,Code,LocalAuthority,Year,Indicator new value,Numerator new value,Denominator new value
13340,CHN19b,Aberdeen City,2024-25,0.89,nan,nan
13349,CHN19b,Aberdeenshire,2024-25,0.85,nan,nan
13358,CHN19b,Angus,2024-25,0.86,nan,nan
13367,CHN19b,Argyll & Bute,2024-25,0.85,nan,nan
13376,CHN19b,Clackmannanshire,2024-25,0.89,nan,nan
...,...,...,...,...,...,...
44303,CLIM02,Scotland,2024-25,3.86,nan,nan
44775,ENV04b,Scotland,2025-26,0.30,nan,nan
44791,ENV04c,Scotland,2025-26,0.33,nan,nan
44807,ENV04d,Scotland,2025-26,0.33,nan,nan
44823,ENV04e,Scotland,2025-26,0.36,nan,nan

#Time to create the change log
##Standardise column names

In [20]:
diffs.columns = diffs.columns.str.strip()
new_Data.columns = new_Data.columns.str.strip()

In [21]:
diffs

                              Indicator_old Numerator_old Denominator_old  \
Code   LocalAuthority Year
C&L02  Aberdeen City  2019-20           nan           nan      1736063.00
                      2020-21           nan           nan       300291.00
                      2021-22           nan           nan      1347180.00
       Aberdeenshire  2019-20           nan           nan      2003318.00
                      2020-21           nan           nan      1125625.00
...                                     ...           ...             ...
CLIM02 Scotland       2020-21          4.17           nan             nan
                      2021-22          4.56           nan             nan
                      2023-24          4.04           nan             nan
ECON04 Scotland       2023-24          0.30           nan             nan
                      2024-25          0.32           nan             nan

                              Indicator_new Numerator_new Denominator_new
Code   LocalAuthority Year
C&L02  Aberdeen City  2019-20          2.17       3764.00      1736063.00
                      2020-21         10.74       3225.00       300291.00
                      2021-22          2.45       3300.00      1347180.00
       Aberdeenshire  2019-20          1.91       3818.00      2003318.00
                      2020-21          3.36       3783.00      1125625.00
...                                     ...           ...             ...
CLIM02 Scotland       2020-21          4.18           nan             nan
                      2021-22          4.58           nan             nan
                      2023-24          4.06           nan             nan
ECON04 Scotland       2023-24          0.31           nan             nan
                      2024-25          0.31           nan             nan

[994 rows x 6 columns]

##Rename columns (diffs → final format)

In [22]:
diffs_renamed = diffs.rename(columns={'Indicator_old': 'Indicator old value','Numerator_old': 'Numerator old value', 'Denominator_old': 'Denominator old value','Indicator_new': 'Indicator new value','Numerator_new': 'Numerator new value', 'Denominator_new': 'Denominator new value'})

In [23]:
diffs_renamed

                              Indicator old value Numerator old value  \
Code   LocalAuthority Year
C&L02  Aberdeen City  2019-20                 nan                 nan
                      2020-21                 nan                 nan
                      2021-22                 nan                 nan
       Aberdeenshire  2019-20                 nan                 nan
                      2020-21                 nan                 nan
...                                           ...                 ...
CLIM02 Scotland       2020-21                4.17                 nan
                      2021-22                4.56                 nan
                      2023-24                4.04                 nan
ECON04 Scotland       2023-24                0.30                 nan
                      2024-25                0.32                 nan

                              Denominator old value Indicator new value  \
Code   LocalAuthority Year
C&L02  Aberdeen City  2019-20            1736063.00                2.17
                      2020-21             300291.00               10.74
                      2021-22            1347180.00                2.45
       Aberdeenshire  2019-20            2003318.00                1.91
                      2020-21            1125625.00                3.36
...                                             ...                 ...
CLIM02 Scotland       2020-21                   nan                4.18
                      2021-22                   nan                4.58
                      2023-24                   nan                4.06
ECON04 Scotland       2023-24                   nan                0.31
                      2024-25                   nan                0.31

                              Numerator new value Denominator new value
Code   LocalAuthority Year
C&L02  Aberdeen City  2019-20             3764.00            1736063.00
                      2020-21             3225.00             300291.00
                      2021-22             3300.00            1347180.00
       Aberdeenshire  2019-20             3818.00            2003318.00
                      2020-21             3783.00            1125625.00
...                                           ...                   ...
CLIM02 Scotland       2020-21                 nan                   nan
                      2021-22                 nan                   nan
                      2023-24                 nan                   nan
ECON04 Scotland       2023-24                 nan                   nan
                      2024-25                 nan                   nan

[994 rows x 6 columns]

In [37]:
new_data_renamed = new_Data.rename(columns={ "Code": "Indicator Code"})

In [38]:
# Add missing OLD columns (since these are new entries)
new_Data["Indicator old value"] = pd.NA
new_Data["Numerator old value"] = pd.NA
new_Data["Denominator old value"] = pd.NA

In [39]:
new_Data

,Code,LocalAuthority,Year,Indicator new value,Numerator new value,Denominator new value,Indicator old value,Numerator old value,Denominator old value
13340,CHN19b,Aberdeen City,2024-25,0.89,nan,nan,<NA>,<NA>,<NA>
13349,CHN19b,Aberdeenshire,2024-25,0.85,nan,nan,<NA>,<NA>,<NA>
13358,CHN19b,Angus,2024-25,0.86,nan,nan,<NA>,<NA>,<NA>
13367,CHN19b,Argyll & Bute,2024-25,0.85,nan,nan,<NA>,<NA>,<NA>
13376,CHN19b,Clackmannanshire,2024-25,0.89,nan,nan,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...
44303,CLIM02,Scotland,2024-25,3.86,nan,nan,<NA>,<NA>,<NA>
44775,ENV04b,Scotland,2025-26,0.30,nan,nan,<NA>,<NA>,<NA>
44791,ENV04c,Scotland,2025-26,0.33,nan,nan,<NA>,<NA>,<NA>
44807,ENV04d,Scotland,2025-26,0.33,nan,nan,<NA>,<NA>,<NA>
44823,ENV04e,Scotland,2025-26,0.36,nan,nan,<NA>,<NA>,<NA>

In [40]:
key_cols = ["Code", "LocalAuthority", "Year"]

In [41]:
diffs_renamed_temp = diffs_renamed.reset_index()
# Create key to compare using original 'Code' column
diffs_keys = diffs_renamed_temp[key_cols].astype(str).agg("|".join, axis=1)
new_keys = new_Data[key_cols].astype(str).agg("|".join, axis=1)

# Ensure 'Code' column is renamed to 'Indicator Code' for consistent concatenation
diffs_renamed_temp = diffs_renamed_temp.rename(columns={"Code": "Indicator Code"})

In [42]:
new_rows_mask = ~new_keys.isin(diffs_keys)
new_rows = new_data_renamed[new_rows_mask].copy()

# Rename new_data columns to match changelog
new_rows = new_rows.rename(columns={
    "Indicator old value": "Indicator old value",
    "Indicator new value": "Indicator new value",
    "Numerator old value": "Numerator old value",
    "Numerator new value": "Numerator new value",
    "Denominator old value": "Denominator old value",
    "Denominator new value": "Denominator new value"
})

In [43]:
new_rows

,Indicator Code,LocalAuthority,Year,Indicator new value,Numerator new value,Denominator new value,Indicator old value,Numerator old value,Denominator old value
13340,CHN19b,Aberdeen City,2024-25,0.89,nan,nan,<NA>,<NA>,<NA>
13349,CHN19b,Aberdeenshire,2024-25,0.85,nan,nan,<NA>,<NA>,<NA>
13358,CHN19b,Angus,2024-25,0.86,nan,nan,<NA>,<NA>,<NA>
13367,CHN19b,Argyll & Bute,2024-25,0.85,nan,nan,<NA>,<NA>,<NA>
13376,CHN19b,Clackmannanshire,2024-25,0.89,nan,nan,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...
44303,CLIM02,Scotland,2024-25,3.86,nan,nan,<NA>,<NA>,<NA>
44775,ENV04b,Scotland,2025-26,0.30,nan,nan,<NA>,<NA>,<NA>
44791,ENV04c,Scotland,2025-26,0.33,nan,nan,<NA>,<NA>,<NA>
44807,ENV04d,Scotland,2025-26,0.33,nan,nan,<NA>,<NA>,<NA>
44823,ENV04e,Scotland,2025-26,0.36,nan,nan,<NA>,<NA>,<NA>

In [44]:
target_cols = [
    "Indicator Code",
    "LocalAuthority",
    "Year",
    "Indicator old value",
    "Numerator old value",
    "Denominator old value",
    "Indicator new value",
    "Numerator new value",
    "Denominator new value"
]

# Ensure diffs_renamed_temp has the correct columns and order
diffs_renamed_temp_aligned = diffs_renamed_temp[target_cols]

# Ensure new_data_renamed has the correct columns and order
new_data_renamed_aligned = new_data_renamed[target_cols]

changelog = pd.concat([diffs_renamed_temp_aligned, new_data_renamed_aligned], ignore_index=True)

In [45]:
changelog

,Indicator Code,LocalAuthority,Year,Indicator old value,Numerator old value,Denominator old value,Indicator new value,Numerator new value,Denominator new value
0,C&L02,Aberdeen City,2019-20,nan,nan,1736063.00,2.17,3764.00,1736063.00
1,C&L02,Aberdeen City,2020-21,nan,nan,300291.00,10.74,3225.00,300291.00
2,C&L02,Aberdeen City,2021-22,nan,nan,1347180.00,2.45,3300.00,1347180.00
3,C&L02,Aberdeenshire,2019-20,nan,nan,2003318.00,1.91,3818.00,2003318.00
4,C&L02,Aberdeenshire,2020-21,nan,nan,1125625.00,3.36,3783.00,1125625.00
...,...,...,...,...,...,...,...,...,...
1249,CLIM02,Scotland,2024-25,<NA>,<NA>,<NA>,3.86,nan,nan
1250,ENV04b,Scotland,2025-26,<NA>,<NA>,<NA>,0.30,nan,nan
1251,ENV04c,Scotland,2025-26,<NA>,<NA>,<NA>,0.33,nan,nan
1252,ENV04d,Scotland,2025-26,<NA>,<NA>,<NA>,0.33,nan,nan
1253,ENV04e,Scotland,2025-26,<NA>,<NA>,<NA>,0.36,nan,nan

In [46]:
from google.colab import files
changelog. to_excel('changelog.xlsx')
files.download('changelog.xlsx')