<a href="https://colab.research.google.com/github/LGBFBenchmarking/ChangeLogMaker/blob/main/Automate_differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Test code for automated output file

#Load files

##new_df is new data including new year's data
##diff_df has old data (no changes or new data for the new year)

In [2]:
import pandas as pd
import numpy as np

def get_data(url): # this function gets data stored as csv file from a given url
  df = pd.read_csv(url)
  return df

In [3]:
url_old = "https://raw.githubusercontent.com/LGBFBenchmarking/ChangeLogMaker/refs/heads/main/LGBF_Data_27Feb26.csv"
url_new = "https://raw.githubusercontent.com/LGBFBenchmarking/ChangeLogMaker/refs/heads/main/LGBF_Data_Mar26.csv"
old_df = get_data(url_old)
new_df = get_data(url_new)

In [4]:
old_df.dtypes

Code               object
LocalAuthority     object
Year               object
Indicator         float64
Numerator         float64
Denominator       float64
dtype: object

In [5]:
new_df.dtypes

Code               object
LocalAuthority     object
Year               object
Indicator         float64
Numerator         float64
Denominator       float64
dtype: object

In [6]:
new_df['Indicator'] = new_df['Indicator'].map("{:.2f}".format)
new_df['Numerator'] = new_df['Numerator'].map('{:.2f}'.format)
new_df['Denominator'] = new_df['Denominator'].map('{:.2f}'.format)

In [7]:
old_df['Indicator'] = old_df['Indicator'].map('{:.2f}'.format)
old_df['Numerator'] = old_df['Numerator'].map('{:.2f}'.format)
old_df['Denominator'] = old_df['Denominator'].map('{:.2f}'.format)

In [8]:
old_df = old_df.round(4)
new_df = new_df.round(4)

In [9]:
old_df.head()

    Code LocalAuthority     Year Indicator Numerator Denominator
0  C&L01  Aberdeen City  2010-11      0.33    637.00  1922292.00
1  C&L01  Aberdeen City  2011-12      0.76   1554.00  2045051.00
2  C&L01  Aberdeen City  2012-13      3.64   7883.00  2163756.00
3  C&L01  Aberdeen City  2013-14      3.48   7726.00  2222588.00
4  C&L01  Aberdeen City  2014-15      3.02   7517.00  2487138.00

In [10]:
new_df.head()

    Code LocalAuthority     Year Indicator Numerator Denominator
0  C&L01  Aberdeen City  2010-11      0.33    637.00  1922292.00
1  C&L01  Aberdeen City  2011-12      0.76   1554.00  2045051.00
2  C&L01  Aberdeen City  2012-13      3.64   7883.00  2163756.00
3  C&L01  Aberdeen City  2013-14      3.48   7726.00  2222588.00
4  C&L01  Aberdeen City  2014-15      3.02   7517.00  2487138.00

In [11]:
df1 = old_df
df2 = new_df

In [12]:
new_set = df2[~df2.astype(str).apply(tuple, 1).isin(df1.astype(str).apply(tuple, 1))]

In [13]:
out = pd.merge(old_df, new_df, on=['Code', 'LocalAuthority', 'Year'], how='outer',
               suffixes=('_old', '_new')).set_index(['Code', 'LocalAuthority', 'Year'])

out.columns = pd.MultiIndex.from_tuples(out.columns.str.split('_').map(tuple)).swaplevel()
out

                                   old                             new  \
                             Indicator Numerator Denominator Indicator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11      0.33    637.00  1922292.00      0.33
                     2011-12      0.76   1554.00  2045051.00      0.76
                     2012-13      3.64   7883.00  2163756.00      3.64
                     2013-14      3.48   7726.00  2222588.00      3.48
                     2014-15      3.02   7517.00  2487138.00      3.02
...                                ...       ...         ...       ...
SW08  West Lothian   2020-21    369.62   4692.00    12694.00    369.62
                     2021-22    439.50   5750.00    13083.00    439.50
                     2022-23    639.84   8856.00    13841.00    639.84
                     2023-24    809.85  11742.00    14499.00    809.85
                     2024-25    960.18  14466.00    15066.00    960.18


                             Numerator Denominator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11    637.00  1922292.00
                     2011-12   1554.00  2045051.00
                     2012-13   7883.00  2163756.00
                     2013-14   7726.00  2222588.00
                     2014-15   7517.00  2487138.00
...                                ...         ...
SW08  West Lothian   2020-21   4692.00    12694.00
                     2021-22   5750.00    13083.00
                     2022-23   8856.00    13841.00
                     2023-24  11742.00    14499.00
                     2024-25  14466.00    15066.00

[44447 rows x 6 columns]

In [14]:
out = out.drop_duplicates(keep=False)
out

                                   old                             new  \
                             Indicator Numerator Denominator Indicator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11      0.33    637.00  1922292.00      0.33
                     2011-12      0.76   1554.00  2045051.00      0.76
                     2012-13      3.64   7883.00  2163756.00      3.64
                     2013-14      3.48   7726.00  2222588.00      3.48
                     2014-15      3.02   7517.00  2487138.00      3.02
...                                ...       ...         ...       ...
SW08  West Lothian   2020-21    369.62   4692.00    12694.00    369.62
                     2021-22    439.50   5750.00    13083.00    439.50
                     2022-23    639.84   8856.00    13841.00    639.84
                     2023-24    809.85  11742.00    14499.00    809.85
                     2024-25    960.18  14466.00    15066.00    960.18


                             Numerator Denominator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11    637.00  1922292.00
                     2011-12   1554.00  2045051.00
                     2012-13   7883.00  2163756.00
                     2013-14   7726.00  2222588.00
                     2014-15   7517.00  2487138.00
...                                ...         ...
SW08  West Lothian   2020-21   4692.00    12694.00
                     2021-22   5750.00    13083.00
                     2022-23   8856.00    13841.00
                     2023-24  11742.00    14499.00
                     2024-25  14466.00    15066.00

[23471 rows x 6 columns]

In [15]:
new_set

         Code LocalAuthority     Year Indicator    Numerator  Denominator
15145   CHN24  Aberdeen City  2023-24      0.12          nan          nan
15146   CHN24  Aberdeen City  2024-25      0.12          nan          nan
15156   CHN24  Aberdeenshire  2023-24      0.10          nan          nan
15157   CHN24  Aberdeenshire  2024-25      0.10          nan          nan
15167   CHN24          Angus  2023-24      0.16          nan          nan
...       ...            ...      ...       ...          ...          ...
43756  CORP11       Scotland  2019-20      1.08  37703627.00  34906301.00
43757  CORP11       Scotland  2020-21      0.83  49350728.00  59483853.00
43758  CORP11       Scotland  2021-22      1.13  53246472.00  47123506.00
43759  CORP11       Scotland  2022-23      1.31  55907146.00  42692331.00
43760  CORP11       Scotland  2023-24      1.29  50184944.00  38751771.00

[363 rows x 6 columns]

In [16]:
from google.colab import files
new_set. to_excel('new_set.xlsx')
files.download('new_set.xlsx')

In [17]:
df1.merge(df2, on=['Code','LocalAuthority','Year'], suffixes=['_old','_new']).drop_duplicates(keep= False) # just a test no need to run this!!!

,Code,LocalAuthority,Year,Indicator_old,Numerator_old,Denominator_old,Indicator_new,Numerator_new,Denominator_new
0,C&L01,Aberdeen City,2010-11,0.33,637.00,1922292.00,0.33,637.00,1922292.00
1,C&L01,Aberdeen City,2011-12,0.76,1554.00,2045051.00,0.76,1554.00,2045051.00
2,C&L01,Aberdeen City,2012-13,3.64,7883.00,2163756.00,3.64,7883.00,2163756.00
3,C&L01,Aberdeen City,2013-14,3.48,7726.00,2222588.00,3.48,7726.00,2222588.00
4,C&L01,Aberdeen City,2014-15,3.02,7517.00,2487138.00,3.02,7517.00,2487138.00
...,...,...,...,...,...,...,...,...,...
44308,SW08,Scotland,2020-21,485.45,227524.00,468682.00,485.45,227524.00,468682.00
44309,SW08,Scotland,2021-22,749.73,357719.00,477131.00,749.73,357719.00,477131.00
44310,SW08,Scotland,2022-23,882.88,439596.00,497909.00,882.88,439596.00,497909.00
44311,SW08,Scotland,2023-24,841.47,431429.00,512706.00,841.47,431429.00,512706.00
44312,SW08,Scotland,2024-25,898.95,474153.00,527454.00,898.95,474153.00,527454.00

In [18]:
def dataframe_difference(df1, df2, which=None):
    """Find rows which are different between two DataFrames."""
    comparison_df = df1.merge(
        df2,
        indicator=True,
        how='outer'
    )
    if which is None:
        diff_df = comparison_df[comparison_df['_merge'] != 'both']  # Identify data changes/updates
    else:
        diff_df = comparison_df[comparison_df['_merge'] == which]
    return diff_df

In [19]:
def getColChangedName(row):
    colsChanged = []
    for c in df1.columns.values:
        if row[c+"_diff"] == True:
            colsChanged.append(c)
    return ", ".join(colsChanged)

In [20]:
df1 = old_df.set_index(['Code', 'LocalAuthority', 'Year'])
df2 = new_set.set_index(['Code','LocalAuthority', 'Year'])

diffs = df1.merge(df2, left_index=True, right_index=True, suffixes=('_old', '_new'))

diff_cols = [c+"_diff" for c in df1.columns.values]

for c in df1.columns.values:
    diffs[c+"_diff"] = diffs[c+"_old"] != diffs[c+"_new"]

diffs["Record_Changed"] = diffs[diff_cols].sum(axis=1)/len(diff_cols) > 0


diffs = diffs[diffs["Record_Changed"] == 1]
diffs["Cols_Changed"] = diffs.apply(lambda row: getColChangedName(row), axis=1)

diffs

                                Indicator_old Numerator_old Denominator_old  \
Code   LocalAuthority   Year
CHN24  Aberdeen City    2023-24          0.19           nan             nan
       Aberdeenshire    2023-24          0.15           nan             nan
       Angus            2023-24          0.24           nan             nan
       Argyll & Bute    2023-24          0.21           nan             nan
       Clackmannanshire 2023-24          0.28           nan             nan
...                                       ...           ...             ...
CORP11 Scotland         2019-20          1.08   37634920.00     34909249.00
                        2020-21          0.83   49461775.00     59456925.00
                        2021-22          1.15   54109502.00     46989736.00
                        2022-23          1.30   56027073.00     42525316.00
                        2023-24          1.29   49947258.00     38734050.00

                                Indicator_new Numerator_new Denominator_new  \
Code   LocalAuthority   Year
CHN24  Aberdeen City    2023-24          0.12           nan             nan
       Aberdeenshire    2023-24          0.10           nan             nan
       Angus            2023-24          0.16           nan             nan
       Argyll & Bute    2023-24          0.15           nan             nan
       Clackmannanshire 2023-24          0.18           nan             nan
...                                       ...           ...             ...
CORP11 Scotland         2019-20          1.08   37703627.00     34906301.00
                        2020-21          0.83   49350728.00     59483853.00
                        2021-22          1.13   53246472.00     47123506.00
                        2022-23          1.31   55907146.00     42692331.00
                        2023-24          1.29   50184944.00     38751771.00

                                 Indicator_diff  Numerator_diff  \
Code   LocalAuthority   Year
CHN24  Aberdeen City    2023-24            True           False
       Aberdeenshire    2023-24            True           False
       Angus            2023-24            True           False
       Argyll & Bute    2023-24            True           False
       Clackmannanshire 2023-24            True           False
...                                         ...             ...
CORP11 Scotland         2019-20           False            True
                        2020-21           False            True
                        2021-22            True            True
                        2022-23            True            True
                        2023-24           False            True

                                 Denominator_diff  Record_Changed  \
Code   LocalAuthority   Year
CHN24  Aberdeen City    2023-24             False            True
       Aberdeenshire    2023-24             False            True
       Angus            2023-24             False            True
       Argyll & Bute    2023-24             False            True
       Clackmannanshire 2023-24             False            True
...                                           ...             ...
CORP11 Scotland         2019-20              True            True
                        2020-21              True            True
                        2021-22              True            True
                        2022-23              True            True
                        2023-24              True            True

                                                      Cols_Changed
Code   LocalAuthority   Year
CHN24  Aberdeen City    2023-24                          Indicator
       Aberdeenshire    2023-24                          Indicator
       Angus            2023-24                          Indicator
       Argyll & Bute    2023-24                          Indicator
       Clackmannanshire 2023-24                          Indicator
...                                                            ...
CORP11 Scotland         2019-20             Numerator, Denominator
                        2020-21             Numerator, Denominator
                        2021-22  Indicator, Numerator, Denominator
                        2022-23  Indicator, Numerator, Denominator
                        2023-24             Numerator, Denominator

[231 rows x 11 columns]

In [21]:
from google.colab import files
diffs. to_excel('diffs.xlsx')
files.download('diffs.xlsx')

In [22]:
old_df

        Code LocalAuthority     Year Indicator  Numerator Denominator
0      C&L01  Aberdeen City  2010-11      0.33     637.00  1922292.00
1      C&L01  Aberdeen City  2011-12      0.76    1554.00  2045051.00
2      C&L01  Aberdeen City  2012-13      3.64    7883.00  2163756.00
3      C&L01  Aberdeen City  2013-14      3.48    7726.00  2222588.00
4      C&L01  Aberdeen City  2014-15      3.02    7517.00  2487138.00
...      ...            ...      ...       ...        ...         ...
44310   SW08       Scotland  2020-21    485.45  227524.00   468682.00
44311   SW08       Scotland  2021-22    749.73  357719.00   477131.00
44312   SW08       Scotland  2022-23    882.88  439596.00   497909.00
44313   SW08       Scotland  2023-24    841.47  431429.00   512706.00
44314   SW08       Scotland  2024-25    898.95  474153.00   527454.00

[44315 rows x 6 columns]

In [23]:
temp = new_df.rename({'Year': 'Year_new'}, axis=1)
temp

        Code LocalAuthority Year_new Indicator  Numerator Denominator
0      C&L01  Aberdeen City  2010-11      0.33     637.00  1922292.00
1      C&L01  Aberdeen City  2011-12      0.76    1554.00  2045051.00
2      C&L01  Aberdeen City  2012-13      3.64    7883.00  2163756.00
3      C&L01  Aberdeen City  2013-14      3.48    7726.00  2222588.00
4      C&L01  Aberdeen City  2014-15      3.02    7517.00  2487138.00
...      ...            ...      ...       ...        ...         ...
44440   SW08       Scotland  2020-21    485.45  227524.00   468682.00
44441   SW08       Scotland  2021-22    749.73  357719.00   477131.00
44442   SW08       Scotland  2022-23    882.88  439596.00   497909.00
44443   SW08       Scotland  2023-24    841.47  431429.00   512706.00
44444   SW08       Scotland  2024-25    898.95  474153.00   527454.00

[44445 rows x 6 columns]

In [24]:
old_df

        Code LocalAuthority     Year Indicator  Numerator Denominator
0      C&L01  Aberdeen City  2010-11      0.33     637.00  1922292.00
1      C&L01  Aberdeen City  2011-12      0.76    1554.00  2045051.00
2      C&L01  Aberdeen City  2012-13      3.64    7883.00  2163756.00
3      C&L01  Aberdeen City  2013-14      3.48    7726.00  2222588.00
4      C&L01  Aberdeen City  2014-15      3.02    7517.00  2487138.00
...      ...            ...      ...       ...        ...         ...
44310   SW08       Scotland  2020-21    485.45  227524.00   468682.00
44311   SW08       Scotland  2021-22    749.73  357719.00   477131.00
44312   SW08       Scotland  2022-23    882.88  439596.00   497909.00
44313   SW08       Scotland  2023-24    841.47  431429.00   512706.00
44314   SW08       Scotland  2024-25    898.95  474153.00   527454.00

[44315 rows x 6 columns]

In [25]:
#find rows with added data from new year
temp = new_df.rename({'Year': 'Year_new'}, axis=1)
#merged = temp.merge(old_df, how='left', left_on=['LocalAuthority','Code','Year_new'], right_on=['LocalAuthority','Code','Year'])
merged = temp.merge(old_df, how='left', left_on=['LocalAuthority','Year_new'], right_on=['LocalAuthority','Year'],indicator='Match')
new_year_df = np.where(merged['Year'].isnull())[0]
new_year_df

array([], dtype=int64)

# create a new data frame with just the new year's data

In [26]:
#new year added data
new_Data = pd.concat([old_df,new_df]).drop_duplicates(subset=["Code", "LocalAuthority", 'Year'], keep=False)

In [27]:
new_Data

         Code LocalAuthority     Year Indicator  Numerator Denominator
5847    CHN06  Argyll & Bute  2024-25      0.00        nan         nan
6242    CHN07  Argyll & Bute  2024-25      0.00        nan         nan
15146   CHN24  Aberdeen City  2024-25      0.12        nan         nan
15157   CHN24  Aberdeenshire  2024-25      0.10        nan         nan
15168   CHN24          Angus  2024-25      0.16        nan         nan
...       ...            ...      ...       ...        ...         ...
17151  CLIM05   West Lothian  2024-25     64.32   11992.58   186440.00
43568   CHN24       Scotland  2024-25      0.15        nan         nan
43604  CLIM03       Scotland  2024-25     29.38  162995.03  5546900.00
43612  CLIM04       Scotland  2024-25     45.60  245756.65  5389900.00
43620  CLIM05       Scotland  2024-25     55.52  299263.02  5389900.00

[134 rows x 6 columns]

In [28]:
from google.colab import files
new_Data. to_excel('new_Data.xlsx')
files.download('new_Data.xlsx')

#Use diff and new_Data to get the Change log