<a href="https://colab.research.google.com/github/LGBFBenchmarking/ChangeLogMaker/blob/main/Automate_differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Test code for automated output file

#Load files

##new_df is new data including new year's data
##diff_df has old data (no changes or new data for the new year)

In [35]:
import pandas as pd
import numpy as np

def get_data(url): # this function gets data stored as csv file from a given url
  df = pd.read_csv(url)
  return df

In [36]:
url_old = "https://raw.githubusercontent.com/LGBFBenchmarking/ChangeLogMaker/refs/heads/main/LGBF_data_Jun26.csv"
url_new = "https://raw.githubusercontent.com/LGBFBenchmarking/ChangeLogMaker/refs/heads/main/LGBF_Data_Jul2026.csv"
old_df = get_data(url_old)
new_df = get_data(url_new)

In [37]:
new_df['Indicator'] = new_df['Indicator'].map("{:.2f}".format)
new_df['Numerator'] = new_df['Numerator'].map('{:.2f}'.format)
new_df['Denominator'] = new_df['Denominator'].map('{:.2f}'.format)

In [38]:
old_df['Indicator'] = old_df['Indicator'].map('{:.2f}'.format)
old_df['Numerator'] = old_df['Numerator'].map('{:.2f}'.format)
old_df['Denominator'] = old_df['Denominator'].map('{:.2f}'.format)

In [39]:
old_df = old_df.round(4)
new_df = new_df.round(4)

In [40]:
df1 = old_df
df2 = new_df

In [41]:
new_set = df2[~df2.astype(str).apply(tuple, 1).isin(df1.astype(str).apply(tuple, 1))]

In [42]:
out = pd.merge(old_df, new_df, on=['Code', 'LocalAuthority', 'Year'], how='outer',
               suffixes=('_old', '_new')).set_index(['Code', 'LocalAuthority', 'Year'])

out.columns = pd.MultiIndex.from_tuples(out.columns.str.split('_').map(tuple)).swaplevel()
out

                                   old                             new  \
                             Indicator Numerator Denominator Indicator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11      0.33    637.00  1922292.00      0.33
                     2011-12      0.76   1554.00  2045051.00      0.76
                     2012-13      3.64   7883.00  2163756.00      3.64
                     2013-14      3.48   7726.00  2222588.00      3.48
                     2014-15      3.02   7517.00  2487138.00      3.02
...                                ...       ...         ...       ...
SW08  West Lothian   2021-22    439.50   5750.00    13083.00    439.50
                     2022-23    639.84   8856.00    13841.00    639.84
                     2023-24    809.85  11742.00    14499.00    809.85
                     2024-25    960.18  14466.00    15066.00    960.18
                     2025-26       NaN       NaN         NaN    629.96


                             Numerator Denominator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11    637.00  1922292.00
                     2011-12   1554.00  2045051.00
                     2012-13   7883.00  2163756.00
                     2013-14   7726.00  2222588.00
                     2014-15   7517.00  2487138.00
...                                ...         ...
SW08  West Lothian   2021-22   5750.00    13083.00
                     2022-23   8856.00    13841.00
                     2023-24  11742.00    14499.00
                     2024-25  14466.00    15066.00
                     2025-26   9491.00    15066.00

[45332 rows x 6 columns]

In [43]:
out = out.drop_duplicates(keep=False)
out

                                   old                             new  \
                             Indicator Numerator Denominator Indicator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11      0.33    637.00  1922292.00      0.33
                     2011-12      0.76   1554.00  2045051.00      0.76
                     2012-13      3.64   7883.00  2163756.00      3.64
                     2013-14      3.48   7726.00  2222588.00      3.48
                     2014-15      3.02   7517.00  2487138.00      3.02
...                                ...       ...         ...       ...
SW08  West Lothian   2021-22    439.50   5750.00    13083.00    439.50
                     2022-23    639.84   8856.00    13841.00    639.84
                     2023-24    809.85  11742.00    14499.00    809.85
                     2024-25    960.18  14466.00    15066.00    960.18
                     2025-26       NaN       NaN         NaN    629.96


                             Numerator Denominator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11    637.00  1922292.00
                     2011-12   1554.00  2045051.00
                     2012-13   7883.00  2163756.00
                     2013-14   7726.00  2222588.00
                     2014-15   7517.00  2487138.00
...                                ...         ...
SW08  West Lothian   2021-22   5750.00    13083.00
                     2022-23   8856.00    13841.00
                     2023-24  11742.00    14499.00
                     2024-25  14466.00    15066.00
                     2025-26   9491.00    15066.00

[23827 rows x 6 columns]

In [44]:
new_set

          Code       LocalAuthority     Year Indicator  Numerator Denominator
1274     C&L03       North Ayrshire  2024-25      0.49      44.00    89649.00
18395  CORP03c        Argyll & Bute  2016-17      0.09      14.51       13.28
18420  CORP03c  Dumfries & Galloway  2021-22      0.04      16.71       15.95
18469  CORP03c    East Renfrewshire  2020-21      0.07      17.60       16.46
18530  CORP03c             Highland  2021-22      0.04      18.11       17.29
...        ...                  ...      ...       ...        ...         ...
45300     SW06             Scotland  2022-23    102.36   97381.00   951400.00
45301     SW06             Scotland  2023-24    104.59  105359.00  1007372.00
45302     SW06             Scotland  2024-25    103.44  105953.00  1024288.00
45303     SW06             Scotland  2025-26    104.24  108880.00  1044523.00
45331     SW08             Scotland  2025-26    873.00  460469.00   527454.00

[881 rows x 6 columns]

In [45]:
df1.merge(df2, on=['Code','LocalAuthority','Year'], suffixes=['_old','_new']).drop_duplicates(keep= False) # just a test no need to run this!!!

,Code,LocalAuthority,Year,Indicator_old,Numerator_old,Denominator_old,Indicator_new,Numerator_new,Denominator_new
0,C&L01,Aberdeen City,2010-11,0.33,637.00,1922292.00,0.33,637.00,1922292.00
1,C&L01,Aberdeen City,2011-12,0.76,1554.00,2045051.00,0.76,1554.00,2045051.00
2,C&L01,Aberdeen City,2012-13,3.64,7883.00,2163756.00,3.64,7883.00,2163756.00
3,C&L01,Aberdeen City,2013-14,3.48,7726.00,2222588.00,3.48,7726.00,2222588.00
4,C&L01,Aberdeen City,2014-15,3.02,7517.00,2487138.00,3.02,7517.00,2487138.00
...,...,...,...,...,...,...,...,...,...
45161,SW08,Scotland,2020-21,485.45,227524.00,468682.00,485.45,227524.00,468682.00
45162,SW08,Scotland,2021-22,749.73,357719.00,477131.00,749.73,357719.00,477131.00
45163,SW08,Scotland,2022-23,882.88,439596.00,497909.00,882.88,439596.00,497909.00
45164,SW08,Scotland,2023-24,841.47,431429.00,512706.00,841.47,431429.00,512706.00
45165,SW08,Scotland,2024-25,898.95,474153.00,527454.00,898.95,474153.00,527454.00

In [46]:
def dataframe_difference(df1, df2, which=None):
    """Find rows which are different between two DataFrames."""
    comparison_df = df1.merge(
        df2,
        indicator=True,
        how='outer'
    )
    if which is None:
        diff_df = comparison_df[comparison_df['_merge'] != 'both']  # Identify data changes/updates
    else:
        diff_df = comparison_df[comparison_df['_merge'] == which]
    return diff_df

In [47]:
def getColChangedName(row):
    colsChanged = []
    for c in df1.columns.values:
        if row[c+"_diff"] == True:
            colsChanged.append(c)
    return ", ".join(colsChanged)

In [48]:
df1 = old_df.set_index(['Code', 'LocalAuthority', 'Year'])
df2 = new_set.set_index(['Code','LocalAuthority', 'Year'])

diffs = df1.merge(df2, left_index=True, right_index=True, suffixes=('_old', '_new'))

diff_cols = [c+"_diff" for c in df1.columns.values]
diffs

                                    Indicator_old Numerator_old  \
Code    LocalAuthority      Year
C&L03   North Ayrshire      2024-25          0.45         44.00
CORP03c Argyll & Bute       2016-17          0.08         14.51
        Dumfries & Galloway 2021-22          0.05         16.71
        East Renfrewshire   2020-21          0.06         17.60
        Highland            2021-22          0.05         18.11
...                                           ...           ...
SW06    Scotland            2020-21        120.27      91993.00
                            2021-22        106.85      98277.00
                            2022-23        102.31      97261.00
                            2023-24        104.43     104963.00
                            2024-25        102.80     104738.00

                                    Denominator_old Indicator_new  \
Code    LocalAuthority      Year
C&L03   North Ayrshire      2024-25        98483.00          0.49
CORP03c Argyll & Bute       2016-17           13.28          0.09
        Dumfries & Galloway 2021-22           15.95          0.04
        East Renfrewshire   2020-21           16.46          0.07
        Highland            2021-22           17.29          0.04
...                                             ...           ...
SW06    Scotland            2020-21       764877.00        120.28
                            2021-22       919768.00        106.86
                            2022-23       950638.00        102.36
                            2023-24      1005096.00        104.59
                            2024-25      1018813.00        103.44

                                    Numerator_new Denominator_new
Code    LocalAuthority      Year
C&L03   North Ayrshire      2024-25         44.00        89649.00
CORP03c Argyll & Bute       2016-17         14.51           13.28
        Dumfries & Galloway 2021-22         16.71           15.95
        East Renfrewshire   2020-21         17.60           16.46
        Highland            2021-22         18.11           17.29
...                                           ...             ...
SW06    Scotland            2020-21      92021.00       765075.00
                            2021-22      98316.00       920064.00
                            2022-23      97381.00       951400.00
                            2023-24     105359.00      1007372.00
                            2024-25     105953.00      1024288.00

[715 rows x 6 columns]

In [49]:
#from google.colab import files
#diffs. to_excel('diffs.xlsx')
#files.download('diffs.xlsx')

In [50]:
temp = new_df.rename({'Year': 'Year_new'}, axis=1)
temp

        Code LocalAuthority Year_new Indicator  Numerator Denominator
0      C&L01  Aberdeen City  2010-11      0.33     637.00  1922292.00
1      C&L01  Aberdeen City  2011-12      0.76    1554.00  2045051.00
2      C&L01  Aberdeen City  2012-13      3.64    7883.00  2163756.00
3      C&L01  Aberdeen City  2013-14      3.48    7726.00  2222588.00
4      C&L01  Aberdeen City  2014-15      3.02    7517.00  2487138.00
...      ...            ...      ...       ...        ...         ...
45327   SW08       Scotland  2021-22    749.73  357719.00   477131.00
45328   SW08       Scotland  2022-23    882.88  439596.00   497909.00
45329   SW08       Scotland  2023-24    841.47  431429.00   512706.00
45330   SW08       Scotland  2024-25    898.95  474153.00   527454.00
45331   SW08       Scotland  2025-26    873.00  460469.00   527454.00

[45332 rows x 6 columns]

# create a new data frame with just the new year's data

In [51]:
#new year added data
new_Data = pd.concat([old_df,new_df]).drop_duplicates(subset=["Code", "LocalAuthority", 'Year'], keep=False)

In [52]:
new_Data

         Code    LocalAuthority     Year Indicator    Numerator  Denominator
21090  CORP09     Aberdeen City  2025-26      0.98      4675.00      4755.00
21098  CORP09     Aberdeenshire  2025-26      0.97      2010.00      2065.00
21106  CORP09             Angus  2025-26      0.98       990.00      1015.00
21114  CORP09     Argyll & Bute  2025-26      1.01       550.00       545.00
21122  CORP09  Clackmannanshire  2025-26      1.00       650.00       650.00
...       ...               ...      ...       ...          ...          ...
44611  CORP09          Scotland  2025-26      0.98     71965.00     73705.00
44619  CORP10          Scotland  2025-26      0.90     18690.00     20745.00
44632  CORP11          Scotland  2025-26      1.02  50974176.00  51977200.00
45303    SW06          Scotland  2025-26    104.24    108880.00   1044523.00
45331    SW08          Scotland  2025-26    873.00    460469.00    527454.00

[166 rows x 6 columns]

In [53]:
new_Data.rename(columns={'Indicator': 'Indicator new value', 'Numerator': 'Numerator new value','Denominator': 'Denominator new value'}, inplace=True)
new_Data

,Code,LocalAuthority,Year,Indicator new value,Numerator new value,Denominator new value
21090,CORP09,Aberdeen City,2025-26,0.98,4675.00,4755.00
21098,CORP09,Aberdeenshire,2025-26,0.97,2010.00,2065.00
21106,CORP09,Angus,2025-26,0.98,990.00,1015.00
21114,CORP09,Argyll & Bute,2025-26,1.01,550.00,545.00
21122,CORP09,Clackmannanshire,2025-26,1.00,650.00,650.00
...,...,...,...,...,...,...
44611,CORP09,Scotland,2025-26,0.98,71965.00,73705.00
44619,CORP10,Scotland,2025-26,0.90,18690.00,20745.00
44632,CORP11,Scotland,2025-26,1.02,50974176.00,51977200.00
45303,SW06,Scotland,2025-26,104.24,108880.00,1044523.00
45331,SW08,Scotland,2025-26,873.00,460469.00,527454.00

#Time to create the change log
##Standardise column names

In [54]:
diffs.columns = diffs.columns.str.strip()
new_Data.columns = new_Data.columns.str.strip()

In [55]:
diffs

                                    Indicator_old Numerator_old  \
Code    LocalAuthority      Year
C&L03   North Ayrshire      2024-25          0.45         44.00
CORP03c Argyll & Bute       2016-17          0.08         14.51
        Dumfries & Galloway 2021-22          0.05         16.71
        East Renfrewshire   2020-21          0.06         17.60
        Highland            2021-22          0.05         18.11
...                                           ...           ...
SW06    Scotland            2020-21        120.27      91993.00
                            2021-22        106.85      98277.00
                            2022-23        102.31      97261.00
                            2023-24        104.43     104963.00
                            2024-25        102.80     104738.00

                                    Denominator_old Indicator_new  \
Code    LocalAuthority      Year
C&L03   North Ayrshire      2024-25        98483.00          0.49
CORP03c Argyll & Bute       2016-17           13.28          0.09
        Dumfries & Galloway 2021-22           15.95          0.04
        East Renfrewshire   2020-21           16.46          0.07
        Highland            2021-22           17.29          0.04
...                                             ...           ...
SW06    Scotland            2020-21       764877.00        120.28
                            2021-22       919768.00        106.86
                            2022-23       950638.00        102.36
                            2023-24      1005096.00        104.59
                            2024-25      1018813.00        103.44

                                    Numerator_new Denominator_new
Code    LocalAuthority      Year
C&L03   North Ayrshire      2024-25         44.00        89649.00
CORP03c Argyll & Bute       2016-17         14.51           13.28
        Dumfries & Galloway 2021-22         16.71           15.95
        East Renfrewshire   2020-21         17.60           16.46
        Highland            2021-22         18.11           17.29
...                                           ...             ...
SW06    Scotland            2020-21      92021.00       765075.00
                            2021-22      98316.00       920064.00
                            2022-23      97381.00       951400.00
                            2023-24     105359.00      1007372.00
                            2024-25     105953.00      1024288.00

[715 rows x 6 columns]

##Rename columns (diffs → final format)

In [56]:
diffs_renamed = diffs.rename(columns={'Indicator_old': 'Indicator old value','Numerator_old': 'Numerator old value', 'Denominator_old': 'Denominator old value','Indicator_new': 'Indicator new value','Numerator_new': 'Numerator new value', 'Denominator_new': 'Denominator new value'})

In [57]:
diffs_renamed

                                    Indicator old value Numerator old value  \
Code    LocalAuthority      Year
C&L03   North Ayrshire      2024-25                0.45               44.00
CORP03c Argyll & Bute       2016-17                0.08               14.51
        Dumfries & Galloway 2021-22                0.05               16.71
        East Renfrewshire   2020-21                0.06               17.60
        Highland            2021-22                0.05               18.11
...                                                 ...                 ...
SW06    Scotland            2020-21              120.27            91993.00
                            2021-22              106.85            98277.00
                            2022-23              102.31            97261.00
                            2023-24              104.43           104963.00
                            2024-25              102.80           104738.00

                                    Denominator old value Indicator new value  \
Code    LocalAuthority      Year
C&L03   North Ayrshire      2024-25              98483.00                0.49
CORP03c Argyll & Bute       2016-17                 13.28                0.09
        Dumfries & Galloway 2021-22                 15.95                0.04
        East Renfrewshire   2020-21                 16.46                0.07
        Highland            2021-22                 17.29                0.04
...                                                   ...                 ...
SW06    Scotland            2020-21             764877.00              120.28
                            2021-22             919768.00              106.86
                            2022-23             950638.00              102.36
                            2023-24            1005096.00              104.59
                            2024-25            1018813.00              103.44

                                    Numerator new value Denominator new value
Code    LocalAuthority      Year
C&L03   North Ayrshire      2024-25               44.00              89649.00
CORP03c Argyll & Bute       2016-17               14.51                 13.28
        Dumfries & Galloway 2021-22               16.71                 15.95
        East Renfrewshire   2020-21               17.60                 16.46
        Highland            2021-22               18.11                 17.29
...                                                 ...                   ...
SW06    Scotland            2020-21            92021.00             765075.00
                            2021-22            98316.00             920064.00
                            2022-23            97381.00             951400.00
                            2023-24           105359.00            1007372.00
                            2024-25           105953.00            1024288.00

[715 rows x 6 columns]

In [58]:
new_data_renamed = new_Data.rename(columns={ "Code": "Indicator Code"})

In [59]:
# Add missing OLD columns (since these are new entries)
new_Data["Indicator old value"] = pd.NA
new_Data["Numerator old value"] = pd.NA
new_Data["Denominator old value"] = pd.NA

In [60]:
new_Data

,Code,LocalAuthority,Year,Indicator new value,Numerator new value,Denominator new value,Indicator old value,Numerator old value,Denominator old value
21090,CORP09,Aberdeen City,2025-26,0.98,4675.00,4755.00,<NA>,<NA>,<NA>
21098,CORP09,Aberdeenshire,2025-26,0.97,2010.00,2065.00,<NA>,<NA>,<NA>
21106,CORP09,Angus,2025-26,0.98,990.00,1015.00,<NA>,<NA>,<NA>
21114,CORP09,Argyll & Bute,2025-26,1.01,550.00,545.00,<NA>,<NA>,<NA>
21122,CORP09,Clackmannanshire,2025-26,1.00,650.00,650.00,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...
44611,CORP09,Scotland,2025-26,0.98,71965.00,73705.00,<NA>,<NA>,<NA>
44619,CORP10,Scotland,2025-26,0.90,18690.00,20745.00,<NA>,<NA>,<NA>
44632,CORP11,Scotland,2025-26,1.02,50974176.00,51977200.00,<NA>,<NA>,<NA>
45303,SW06,Scotland,2025-26,104.24,108880.00,1044523.00,<NA>,<NA>,<NA>
45331,SW08,Scotland,2025-26,873.00,460469.00,527454.00,<NA>,<NA>,<NA>

In [61]:
key_cols = ["Code", "LocalAuthority", "Year"]

In [62]:
diffs_renamed_temp = diffs_renamed.reset_index()
# Create key to compare using original 'Code' column
diffs_keys = diffs_renamed_temp[key_cols].astype(str).agg("|".join, axis=1)
new_keys = new_Data[key_cols].astype(str).agg("|".join, axis=1)

# Ensure 'Code' column is renamed to 'Indicator Code' for consistent concatenation
diffs_renamed_temp = diffs_renamed_temp.rename(columns={"Code": "Indicator Code"})

In [63]:
new_rows_mask = ~new_keys.isin(diffs_keys)
new_rows = new_data_renamed[new_rows_mask].copy()

# Rename new_data columns to match changelog
new_rows = new_rows.rename(columns={
    "Indicator old value": "Indicator old value",
    "Indicator new value": "Indicator new value",
    "Numerator old value": "Numerator old value",
    "Numerator new value": "Numerator new value",
    "Denominator old value": "Denominator old value",
    "Denominator new value": "Denominator new value"
})

In [64]:
new_rows

,Indicator Code,LocalAuthority,Year,Indicator new value,Numerator new value,Denominator new value
21090,CORP09,Aberdeen City,2025-26,0.98,4675.00,4755.00
21098,CORP09,Aberdeenshire,2025-26,0.97,2010.00,2065.00
21106,CORP09,Angus,2025-26,0.98,990.00,1015.00
21114,CORP09,Argyll & Bute,2025-26,1.01,550.00,545.00
21122,CORP09,Clackmannanshire,2025-26,1.00,650.00,650.00
...,...,...,...,...,...,...
44611,CORP09,Scotland,2025-26,0.98,71965.00,73705.00
44619,CORP10,Scotland,2025-26,0.90,18690.00,20745.00
44632,CORP11,Scotland,2025-26,1.02,50974176.00,51977200.00
45303,SW06,Scotland,2025-26,104.24,108880.00,1044523.00
45331,SW08,Scotland,2025-26,873.00,460469.00,527454.00

In [65]:
target_cols = [
    "Indicator Code",
    "LocalAuthority",
    "Year",
    "Indicator old value",
    "Numerator old value",
    "Denominator old value",
    "Indicator new value",
    "Numerator new value",
    "Denominator new value"
]

# Ensure diffs_renamed_temp has the correct columns and order
diffs_renamed_temp_aligned = diffs_renamed_temp[target_cols]

# Reconstruct new_data_renamed_aligned to include all target_cols and apply the filter
# Start with new_Data which has the 'old' columns and 'new' columns.
# Apply the new_rows_mask to filter for truly new rows.
# Rename the 'Code' column to 'Indicator Code'.
temp_new_data = new_Data[new_rows_mask].copy()
new_data_renamed_aligned = temp_new_data.rename(columns={"Code": "Indicator Code"})[target_cols]

changelog = pd.concat([diffs_renamed_temp_aligned, new_data_renamed_aligned], ignore_index=True)

In [66]:
changelog

,Indicator Code,LocalAuthority,Year,Indicator old value,Numerator old value,Denominator old value,Indicator new value,Numerator new value,Denominator new value
0,C&L03,North Ayrshire,2024-25,0.45,44.00,98483.00,0.49,44.00,89649.00
1,CORP03c,Argyll & Bute,2016-17,0.08,14.51,13.28,0.09,14.51,13.28
2,CORP03c,Dumfries & Galloway,2021-22,0.05,16.71,15.95,0.04,16.71,15.95
3,CORP03c,East Renfrewshire,2020-21,0.06,17.60,16.46,0.07,17.60,16.46
4,CORP03c,Highland,2021-22,0.05,18.11,17.29,0.04,18.11,17.29
...,...,...,...,...,...,...,...,...,...
876,CORP09,Scotland,2025-26,<NA>,<NA>,<NA>,0.98,71965.00,73705.00
877,CORP10,Scotland,2025-26,<NA>,<NA>,<NA>,0.90,18690.00,20745.00
878,CORP11,Scotland,2025-26,<NA>,<NA>,<NA>,1.02,50974176.00,51977200.00
879,SW06,Scotland,2025-26,<NA>,<NA>,<NA>,104.24,108880.00,1044523.00
880,SW08,Scotland,2025-26,<NA>,<NA>,<NA>,873.00,460469.00,527454.00

In [67]:
from google.colab import files
changelog. to_excel('changelog.xlsx')
files.download('changelog.xlsx')