<a href="https://colab.research.google.com/github/LGBFBenchmarking/ChangeLogMaker/blob/main/Automate_differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Test code for automated output file

#Load files

##new_df is new data including new year's data
##diff_df has old data (no changes or new data for the new year)

In [1]:
import pandas as pd
import numpy as np

def get_data(url): # this function gets data stored as csv file from a given url
  df = pd.read_csv(url)
  return df

In [2]:
url_old = "https://raw.githubusercontent.com/LGBFBenchmarking/ChangeLogMaker/refs/heads/main/LGBF_Data_Feb26.csv"
url_new = "https://raw.githubusercontent.com/LGBFBenchmarking/ChangeLogMaker/refs/heads/main/LGBF_Data_27Feb26.csv"
old_df = get_data(url_old)
new_df = get_data(url_new)

In [3]:
old_df.dtypes

Code               object
LocalAuthority     object
Year               object
Indicator         float64
Numerator         float64
Denominator       float64
dtype: object

In [4]:
new_df.dtypes

Code               object
LocalAuthority     object
Year               object
Indicator         float64
Numerator         float64
Denominator       float64
dtype: object

In [5]:
new_df['Indicator'] = new_df['Indicator'].map("{:.2f}".format)
new_df['Numerator'] = new_df['Numerator'].map('{:.2f}'.format)
new_df['Denominator'] = new_df['Denominator'].map('{:.2f}'.format)

In [6]:
old_df['Indicator'] = old_df['Indicator'].map('{:.2f}'.format)
old_df['Numerator'] = old_df['Numerator'].map('{:.2f}'.format)
old_df['Denominator'] = old_df['Denominator'].map('{:.2f}'.format)

In [7]:
old_df = old_df.round(4)
new_df = new_df.round(4)

In [8]:
old_df.head()

    Code LocalAuthority     Year Indicator Numerator Denominator
0  C&L01  Aberdeen City  2010-11      0.33    637.00  1922292.00
1  C&L01  Aberdeen City  2011-12      0.76   1554.00  2045051.00
2  C&L01  Aberdeen City  2012-13      3.64   7883.00  2163756.00
3  C&L01  Aberdeen City  2013-14      3.48   7726.00  2222588.00
4  C&L01  Aberdeen City  2014-15      3.02   7517.00  2487138.00

In [9]:
new_df.head()

    Code LocalAuthority     Year Indicator Numerator Denominator
0  C&L01  Aberdeen City  2010-11      0.33    637.00  1922292.00
1  C&L01  Aberdeen City  2011-12      0.76   1554.00  2045051.00
2  C&L01  Aberdeen City  2012-13      3.64   7883.00  2163756.00
3  C&L01  Aberdeen City  2013-14      3.48   7726.00  2222588.00
4  C&L01  Aberdeen City  2014-15      3.02   7517.00  2487138.00

In [10]:
df1 = old_df
df2 = new_df

In [11]:
new_set = df2[~df2.astype(str).apply(tuple, 1).isin(df1.astype(str).apply(tuple, 1))]

In [12]:
out = pd.merge(old_df, new_df, on=['Code', 'LocalAuthority', 'Year'], how='outer',
               suffixes=('_old', '_new')).set_index(['Code', 'LocalAuthority', 'Year'])

out.columns = pd.MultiIndex.from_tuples(out.columns.str.split('_').map(tuple)).swaplevel()
out

                                   old                             new  \
                             Indicator Numerator Denominator Indicator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11      0.33    637.00  1922292.00      0.33
                     2011-12      0.76   1554.00  2045051.00      0.76
                     2012-13      3.64   7883.00  2163756.00      3.64
                     2013-14      3.48   7726.00  2222588.00      3.48
                     2014-15      3.02   7517.00  2487138.00      3.02
...                                ...       ...         ...       ...
SW08  West Lothian   2020-21    369.62   4692.00    12694.00    369.62
                     2021-22    439.50   5750.00    13083.00    439.50
                     2022-23    639.84   8856.00    13841.00    639.84
                     2023-24    809.85  11742.00    14499.00    809.85
                     2024-25    960.18  14466.00    15066.00    960.18


                             Numerator Denominator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11    637.00  1922292.00
                     2011-12   1554.00  2045051.00
                     2012-13   7883.00  2163756.00
                     2013-14   7726.00  2222588.00
                     2014-15   7517.00  2487138.00
...                                ...         ...
SW08  West Lothian   2020-21   4692.00    12694.00
                     2021-22   5750.00    13083.00
                     2022-23   8856.00    13841.00
                     2023-24  11742.00    14499.00
                     2024-25  14466.00    15066.00

[44341 rows x 6 columns]

In [13]:
out = out.drop_duplicates(keep=False)
out

                                   old                             new  \
                             Indicator Numerator Denominator Indicator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11      0.33    637.00  1922292.00      0.33
                     2011-12      0.76   1554.00  2045051.00      0.76
                     2012-13      3.64   7883.00  2163756.00      3.64
                     2013-14      3.48   7726.00  2222588.00      3.48
                     2014-15      3.02   7517.00  2487138.00      3.02
...                                ...       ...         ...       ...
SW08  West Lothian   2020-21    369.62   4692.00    12694.00    369.62
                     2021-22    439.50   5750.00    13083.00    439.50
                     2022-23    639.84   8856.00    13841.00    639.84
                     2023-24    809.85  11742.00    14499.00    809.85
                     2024-25    960.18  14466.00    15066.00    960.18


                             Numerator Denominator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11    637.00  1922292.00
                     2011-12   1554.00  2045051.00
                     2012-13   7883.00  2163756.00
                     2013-14   7726.00  2222588.00
                     2014-15   7517.00  2487138.00
...                                ...         ...
SW08  West Lothian   2020-21   4692.00    12694.00
                     2021-22   5750.00    13083.00
                     2022-23   8856.00    13841.00
                     2023-24  11742.00    14499.00
                     2024-25  14466.00    15066.00

[23369 rows x 6 columns]

In [14]:
new_set

           Code    LocalAuthority     Year Indicator    Numerator  Denominator
4909      CHN04     Aberdeen City  2024-25      0.71          nan          nan
4923      CHN04     Aberdeenshire  2024-25      0.67          nan          nan
4937      CHN04             Angus  2024-25      0.63          nan          nan
4951      CHN04     Argyll & Bute  2024-25      0.64          nan          nan
4965      CHN04  Clackmannanshire  2024-25      0.58          nan          nan
...         ...               ...      ...       ...          ...          ...
43173     CHN07          Scotland  2024-25      0.24          nan          nan
43243     CHN11          Scotland  2024-25      0.96          nan          nan
43645    CORP11          Scotland  2024-25      0.83  46560293.00  56148275.00
43695    ECON01          Scotland  2023-24      0.12     11244.00     95400.00
44088  FINSUS01          Scotland  2024-25      0.20          nan          nan

[229 rows x 6 columns]

In [15]:
from google.colab import files
new_set. to_excel('new_set.xlsx')
files.download('new_set.xlsx')

In [16]:
df1.merge(df2, on=['Code','LocalAuthority','Year'], suffixes=['_old','_new']).drop_duplicates(keep= False) # just a test no need to run this!!!

,Code,LocalAuthority,Year,Indicator_old,Numerator_old,Denominator_old,Indicator_new,Numerator_new,Denominator_new
0,C&L01,Aberdeen City,2010-11,0.33,637.00,1922292.00,0.33,637.00,1922292.00
1,C&L01,Aberdeen City,2011-12,0.76,1554.00,2045051.00,0.76,1554.00,2045051.00
2,C&L01,Aberdeen City,2012-13,3.64,7883.00,2163756.00,3.64,7883.00,2163756.00
3,C&L01,Aberdeen City,2013-14,3.48,7726.00,2222588.00,3.48,7726.00,2222588.00
4,C&L01,Aberdeen City,2014-15,3.02,7517.00,2487138.00,3.02,7517.00,2487138.00
...,...,...,...,...,...,...,...,...,...
44149,SW08,Scotland,2020-21,485.45,227524.00,468682.00,485.45,227524.00,468682.00
44150,SW08,Scotland,2021-22,749.73,357719.00,477131.00,749.73,357719.00,477131.00
44151,SW08,Scotland,2022-23,882.88,439596.00,497909.00,882.88,439596.00,497909.00
44152,SW08,Scotland,2023-24,841.47,431429.00,512706.00,841.47,431429.00,512706.00
44153,SW08,Scotland,2024-25,898.95,474153.00,527454.00,898.95,474153.00,527454.00

In [17]:
def dataframe_difference(df1, df2, which=None):
    """Find rows which are different between two DataFrames."""
    comparison_df = df1.merge(
        df2,
        indicator=True,
        how='outer'
    )
    if which is None:
        diff_df = comparison_df[comparison_df['_merge'] != 'both']  # Identify data changes/updates
    else:
        diff_df = comparison_df[comparison_df['_merge'] == which]
    return diff_df

In [18]:
def getColChangedName(row):
    colsChanged = []
    for c in df1.columns.values:
        if row[c+"_diff"] == True:
            colsChanged.append(c)
    return ", ".join(colsChanged)

In [19]:
df1 = old_df.set_index(['Code', 'LocalAuthority', 'Year'])
df2 = new_set.set_index(['Code','LocalAuthority', 'Year'])

diffs = df1.merge(df2, left_index=True, right_index=True, suffixes=('_old', '_new'))

diff_cols = [c+"_diff" for c in df1.columns.values]

for c in df1.columns.values:
    diffs[c+"_diff"] = diffs[c+"_old"] != diffs[c+"_new"]

diffs["Record_Changed"] = diffs[diff_cols].sum(axis=1)/len(diff_cols) > 0


diffs = diffs[diffs["Record_Changed"] == 1]
diffs["Cols_Changed"] = diffs.apply(lambda row: getColChangedName(row), axis=1)

diffs

                                     Indicator_old Numerator_old  \
Code     LocalAuthority      Year
CHN11    Angus               2014-15          0.94           nan
         Clackmannanshire    2016-17          0.88           nan
         East Dunbartonshire 2019-20          0.97           nan
         East Lothian        2019-20          0.93           nan
         Edinburgh City      2014-15          0.93           nan
                             2019-20          0.93           nan
         Highland            2019-20          0.93           nan
         North Ayrshire      2022-23          0.96           nan
         Orkney Islands      2020-21          0.96           nan
         Perth & Kinross     2011-12          0.94           nan
                             2020-21          0.96           nan
         Renfrewshire        2020-21          0.96           nan
         Scottish Borders    2015-16          0.94           nan
         South Ayrshire      2014-15          0.94           nan
         West Lothian        2017-18          0.94           nan
CORP11   Aberdeen City       2024-25          1.19    1587817.00
         Aberdeenshire       2024-25          1.51    1343324.00
         Angus               2024-25          1.27     954459.00
         Argyll & Bute       2024-25          1.26     684527.00
         Clackmannanshire    2024-25          1.33     591000.00
         Dumfries & Galloway 2024-25          1.04    1382738.00
         Dundee City         2024-25          1.05    1974606.00
         East Ayrshire       2024-25          1.05    1499764.00
         East Dunbartonshire 2024-25          1.24     626448.00
         East Lothian        2024-25          1.20     866974.00
         East Renfrewshire   2024-25          0.75     520237.00
         Edinburgh City      2024-25          1.32    3609686.00
         Eilean Siar         2024-25          5.49     593103.00
         Falkirk             2024-25          2.13    1991654.00
         Fife                2024-25          0.73    3591528.00
         Glasgow City        2024-25          1.07    9694189.00
         Highland            2024-25          3.06    3486523.00
         Inverclyde          2024-25          1.31    1134367.00
         Midlothian          2024-25          0.91     788000.00
         Moray               2024-25          1.68     657290.00
         North Ayrshire      2024-25          2.09    2452180.00
         North Lanarkshire   2024-25          1.19    4120844.00
         Orkney Islands      2024-25          1.29     135694.00
         Perth & Kinross     2024-25          0.69     975053.00
         Renfrewshire        2024-25          1.03    1869264.00
         Scottish Borders    2024-25          1.29     875185.00
         Shetland Islands    2024-25          1.65     103474.00
         South Ayrshire      2024-25          1.17    1116711.00
         South Lanarkshire   2024-25          1.21    3294660.00
         Stirling            2024-25          1.03     660027.00
         West Dunbartonshire 2024-25          1.37    1273790.00
         West Lothian        2024-25          1.52    1693159.00
ECON01   Dumfries & Galloway 2023-24          0.29        649.00
         East Renfrewshire   2023-24          0.48        622.00
FINSUS01 Eilean Siar         2024-25          0.00           nan
FINSUS02 Eilean Siar         2024-25          0.00           nan
CORP11   Scotland            2024-25          1.21   56148275.00
ECON01   Scotland            2023-24          0.13      12247.00
FINSUS01 Scotland            2024-25          0.19           nan

                                     Denominator_old Indicator_new  \
Code     LocalAuthority      Year
CHN11    Angus               2014-15             nan          0.95
         Clackmannanshire    2016-17             nan          0.87
         East Dunbartonshire 2019-20             nan          0.98
         East Lothian        2019-20             nan          0.92
         Edinburgh City      2014-15             nan          0.92
                             2019-20             nan          0.92
         Highland            2019-20             nan          0.92
         North Ayrshire      2022-23             nan          0.97
         Orkney Islands      2020-21             nan          0.97
         Perth & Kinross     2011-12             nan          0.93
                             2020-21             nan          0.97
         Renfrewshire        2020-21             nan          0.97
         Scottish Borders    2015-16             nan          0.95
         South Ayrshire      2014-15             nan          0.95
         West Lothian        2017-18             nan          0.95
CORP11   Aberdeen City       2024-25      1339514.00          0.84
         Aberdeenshire       2024-25       890299.00          0.66
         Angus               2024-25       749639.00          0.79
         Argyll & Bute       2024-25       541834.00          0.79
         Clackmannanshire    2024-25       446019.00          0.75
         Dumfries & Galloway 2024-25      1330490.00          0.96
         Dundee City         2024-25      1887082.00          0.96
         East Ayrshire       2024-25      1423244.00          0.95
         East Dunbartonshire 2024-25       504526.00          0.81
         East Lothian        2024-25       724831.00          0.84
         East Renfrewshire   2024-25       693431.00          1.33
         Edinburgh City      2024-25      2724599.00          0.75
         Eilean Siar         2024-25       108004.00          0.18
         Falkirk             2024-25       934345.00          0.47
         Fife                2024-25      4933593.00          1.37
         Glasgow City        2024-25      9019316.00          0.93
         Highland            2024-25      1140728.00          0.33
         Inverclyde          2024-25       863954.00          0.76
         Midlothian          2024-25       862461.00          1.09
         Moray               2024-25       391844.00          0.60
         North Ayrshire      2024-25      1174520.00          0.48
         North Lanarkshire   2024-25      3457533.00          0.84
         Orkney Islands      2024-25       104989.00          0.77
         Perth & Kinross     2024-25      1412796.00          1.45
         Renfrewshire        2024-25      1806796.00          0.97
         Scottish Borders    2024-25       677576.00          0.77
         Shetland Islands    2024-25        62758.00          0.61
         South Ayrshire      2024-25       954765.00          0.85
         South Lanarkshire   2024-25      2713489.00          0.82
         Stirling            2024-25       639757.00          0.97
         West Dunbartonshire 2024-25       929192.00          0.73
         West Lothian        2024-25      1116370.00          0.66
ECON01   Dumfries & Galloway 2023-24         2200.00          0.06
         East Renfrewshire   2023-24         1300.00          0.11
FINSUS01 Eilean Siar         2024-25             nan          0.34
FINSUS02 Eilean Siar         2024-25             nan          0.03
CORP11   Scotland            2024-25     46560293.00          0.83
ECON01   Scotland            2023-24        95400.00          0.12
FINSUS01 Scotland            2024-25             nan          0.20

                                     Numerator_new Denominator_new  \
Code     LocalAuthority      Year
CHN11    Angus               2014-15           nan             nan
         Clackmannanshire    2016-17           nan             nan
         East Dunbartonshire 2019-20           nan             nan
         East Lothian        2019-20           nan             nan
         Edinburgh City      2014-15           nan             nan
                             2019-20           nan             nan
         Highland            2019-20           nan             nan
         North Ayrshire      2022-23           nan             nan
         Orkney Islands      2020-21           nan             nan
         Perth & Kinross     2011-12           nan             nan
                             2020-21           nan             nan
         Renfrewshire        2020-21           nan             nan
         Scottish Borders    2015-16           nan             nan
         South Ayrshire      2014-15           nan             nan
         West Lothian        2017-18           nan             nan
CORP11   Aberdeen City       2024-25    1339514.00      1587817.00
         Aberdeenshire       2024-25     890299.00      1343324.00
         Angus               2024-25     749639.00       954459.00
         Argyll & Bute       2024-25     541834.00       684527.00
         Clackmannanshire    2024-25     446019.00       591000.00
         Dumfries & Galloway 2024-25    1330490.00      1382738.00
         Dundee City         2024-25    1887082.00      1974606.00
         East Ayrshire       2024-25    1423244.00      1499764.00
         East Dunbartonshire 2024-25     504526.00       626448.00
         East Lothian        2024-25     724831.00       866974.00
         East Renfrewshire   2024-25     693431.00       520237.00
         Edinburgh City      2024-25    2724599.00      3609686.00
         Eilean Siar         2024-25     108004.00       593103.00
         Falkirk             2024-25     934345.00      1991654.00
         Fife                2024-25    4933593.00      3591528.00
         Glasgow City        2024-25    9019316.00      9694189.00
         Highland            2024-25    1140728.00      3486523.00
         Inverclyde          2024-25     863954.00      1134367.00
         Midlothian          2024-25     862461.00       788000.00
         Moray               2024-25     391844.00       657290.00
         North Ayrshire      2024-25    1174520.00      2452180.00
         North Lanarkshire   2024-25    3457533.00      4120844.00
         Orkney Islands      2024-25     104989.00       135694.00
         Perth & Kinross     2024-25    1412796.00       975053.00
         Renfrewshire        2024-25    1806796.00      1869264.00
         Scottish Borders    2024-25     677576.00       875185.00
         Shetland Islands    2024-25      62758.00       103474.00
         South Ayrshire      2024-25     954765.00      1116711.00
         South Lanarkshire   2024-25    2713489.00      3294660.00
         Stirling            2024-25     639757.00       660027.00
         West Dunbartonshire 2024-25     929192.00      1273790.00
         West Lothian        2024-25    1116370.00      1693159.00
ECON01   Dumfries & Galloway 2023-24        124.00         2200.00
         East Renfrewshire   2023-24        144.00         1300.00
FINSUS01 Eilean Siar         2024-25           nan             nan
FINSUS02 Eilean Siar         2024-25           nan             nan
CORP11   Scotland            2024-25   46560293.00     56148275.00
ECON01   Scotland            2023-24      11244.00        95400.00
FINSUS01 Scotland            2024-25           nan             nan

                                      Indicator_diff  Numerator_diff  \
Code     LocalAuthority      Year
CHN11    Angus               2014-15            True           False
         Clackmannanshire    2016-17            True           False
         East Dunbartonshire 2019-20            True           False
         East Lothian        2019-20            True           False
         Edinburgh City      2014-15            True           False
                             2019-20            True           False
         Highland            2019-20            True           False
         North Ayrshire      2022-23            True           False
         Orkney Islands      2020-21            True           False
         Perth & Kinross     2011-12            True           False
                             2020-21            True           False
         Renfrewshire        2020-21            True           False
         Scottish Borders    2015-16            True           False
         South Ayrshire      2014-15            True           False
         West Lothian        2017-18            True           False
CORP11   Aberdeen City       2024-25            True            True
         Aberdeenshire       2024-25            True            True
         Angus               2024-25            True            True
         Argyll & Bute       2024-25            True            True
         Clackmannanshire    2024-25            True            True
         Dumfries & Galloway 2024-25            True            True
         Dundee City         2024-25            True            True
         East Ayrshire       2024-25            True            True
         East Dunbartonshire 2024-25            True            True
         East Lothian        2024-25            True            True
         East Renfrewshire   2024-25            True            True
         Edinburgh City      2024-25            True            True
         Eilean Siar         2024-25            True            True
         Falkirk             2024-25            True            True
         Fife                2024-25            True            True
         Glasgow City        2024-25            True            True
         Highland            2024-25            True            True
         Inverclyde          2024-25            True            True
         Midlothian          2024-25            True            True
         Moray               2024-25            True            True
         North Ayrshire      2024-25            True            True
         North Lanarkshire   2024-25            True            True
         Orkney Islands      2024-25            True            True
         Perth & Kinross     2024-25            True            True
         Renfrewshire        2024-25            True            True
         Scottish Borders    2024-25            True            True
         Shetland Islands    2024-25            True            True
         South Ayrshire      2024-25            True            True
         South Lanarkshire   2024-25            True            True
         Stirling            2024-25            True            True
         West Dunbartonshire 2024-25            True            True
         West Lothian        2024-25            True            True
ECON01   Dumfries & Galloway 2023-24            True            True
         East Renfrewshire   2023-24            True            True
FINSUS01 Eilean Siar         2024-25            True           False
FINSUS02 Eilean Siar         2024-25            True           False
CORP11   Scotland            2024-25            True            True
ECON01   Scotland            2023-24            True            True
FINSUS01 Scotland            2024-25            True           False

                                      Denominator_diff  Record_Changed  \
Code     LocalAuthority      Year
CHN11    Angus               2014-15             False            True
         Clackmannanshire    2016-17             False            True
         East Dunbartonshire 2019-20             False            True
         East Lothian        2019-20             False            True
         Edinburgh City      2014-15             False            True
                             2019-20             False            True
         Highland            2019-20             False            True
         North Ayrshire      2022-23             False            True
         Orkney Islands      2020-21             False            True
         Perth & Kinross     2011-12             False            True
                             2020-21             False            True
         Renfrewshire        2020-21             False            True
         Scottish Borders    2015-16             False            True
         South Ayrshire      2014-15             False            True
         West Lothian        2017-18             False            True
CORP11   Aberdeen City       2024-25              True            True
         Aberdeenshire       2024-25              True            True
         Angus               2024-25              True            True
         Argyll & Bute       2024-25              True            True
         Clackmannanshire    2024-25              True            True
         Dumfries & Galloway 2024-25              True            True
         Dundee City         2024-25              True            True
         East Ayrshire       2024-25              True            True
         East Dunbartonshire 2024-25              True            True
         East Lothian        2024-25              True            True
         East Renfrewshire   2024-25              True            True
         Edinburgh City      2024-25              True            True
         Eilean Siar         2024-25              True            True
         Falkirk             2024-25              True            True
         Fife                2024-25              True            True
         Glasgow City        2024-25              True            True
         Highland            2024-25              True            True
         Inverclyde          2024-25              True            True
         Midlothian          2024-25              True            True
         Moray               2024-25              True            True
         North Ayrshire      2024-25              True            True
         North Lanarkshire   2024-25              True            True
         Orkney Islands      2024-25              True            True
         Perth & Kinross     2024-25              True            True
         Renfrewshire        2024-25              True            True
         Scottish Borders    2024-25              True            True
         Shetland Islands    2024-25              True            True
         South Ayrshire      2024-25              True            True
         South Lanarkshire   2024-25              True            True
         Stirling            2024-25              True            True
         West Dunbartonshire 2024-25              True            True
         West Lothian        2024-25              True            True
ECON01   Dumfries & Galloway 2023-24             False            True
         East Renfrewshire   2023-24             False            True
FINSUS01 Eilean Siar         2024-25             False            True
FINSUS02 Eilean Siar         2024-25             False            True
CORP11   Scotland            2024-25              True            True
ECON01   Scotland            2023-24             False            True
FINSUS01 Scotland            2024-25             False            True

                                                           Cols_Changed
Code     LocalAuthority      Year
CHN11    Angus               2014-15                          Indicator
         Clackmannanshire    2016-17                          Indicator
         East Dunbartonshire 2019-20                          Indicator
         East Lothian        2019-20                          Indicator
         Edinburgh City      2014-15                          Indicator
                             2019-20                          Indicator
         Highland            2019-20                          Indicator
         North Ayrshire      2022-23                          Indicator
         Orkney Islands      2020-21                          Indicator
         Perth & Kinross     2011-12                          Indicator
                             2020-21                          Indicator
         Renfrewshire        2020-21                          Indicator
         Scottish Borders    2015-16                          Indicator
         South Ayrshire      2014-15                          Indicator

In [20]:
from google.colab import files
diffs. to_excel('diffs.xlsx')
files.download('diffs.xlsx')

In [21]:
old_df

        Code LocalAuthority     Year Indicator  Numerator Denominator
0      C&L01  Aberdeen City  2010-11      0.33     637.00  1922292.00
1      C&L01  Aberdeen City  2011-12      0.76    1554.00  2045051.00
2      C&L01  Aberdeen City  2012-13      3.64    7883.00  2163756.00
3      C&L01  Aberdeen City  2013-14      3.48    7726.00  2222588.00
4      C&L01  Aberdeen City  2014-15      3.02    7517.00  2487138.00
...      ...            ...      ...       ...        ...         ...
44161   SW08       Scotland  2020-21    485.45  227524.00   468682.00
44162   SW08       Scotland  2021-22    749.73  357719.00   477131.00
44163   SW08       Scotland  2022-23    882.88  439596.00   497909.00
44164   SW08       Scotland  2023-24    841.47  431429.00   512706.00
44165   SW08       Scotland  2024-25    898.95  474153.00   527454.00

[44166 rows x 6 columns]

In [22]:
temp = new_df.rename({'Year': 'Year_new'}, axis=1)
temp

        Code LocalAuthority Year_new Indicator  Numerator Denominator
0      C&L01  Aberdeen City  2010-11      0.33     637.00  1922292.00
1      C&L01  Aberdeen City  2011-12      0.76    1554.00  2045051.00
2      C&L01  Aberdeen City  2012-13      3.64    7883.00  2163756.00
3      C&L01  Aberdeen City  2013-14      3.48    7726.00  2222588.00
4      C&L01  Aberdeen City  2014-15      3.02    7517.00  2487138.00
...      ...            ...      ...       ...        ...         ...
44324   SW08       Scotland  2020-21    485.45  227524.00   468682.00
44325   SW08       Scotland  2021-22    749.73  357719.00   477131.00
44326   SW08       Scotland  2022-23    882.88  439596.00   497909.00
44327   SW08       Scotland  2023-24    841.47  431429.00   512706.00
44328   SW08       Scotland  2024-25    898.95  474153.00   527454.00

[44329 rows x 6 columns]

In [23]:
old_df

        Code LocalAuthority     Year Indicator  Numerator Denominator
0      C&L01  Aberdeen City  2010-11      0.33     637.00  1922292.00
1      C&L01  Aberdeen City  2011-12      0.76    1554.00  2045051.00
2      C&L01  Aberdeen City  2012-13      3.64    7883.00  2163756.00
3      C&L01  Aberdeen City  2013-14      3.48    7726.00  2222588.00
4      C&L01  Aberdeen City  2014-15      3.02    7517.00  2487138.00
...      ...            ...      ...       ...        ...         ...
44161   SW08       Scotland  2020-21    485.45  227524.00   468682.00
44162   SW08       Scotland  2021-22    749.73  357719.00   477131.00
44163   SW08       Scotland  2022-23    882.88  439596.00   497909.00
44164   SW08       Scotland  2023-24    841.47  431429.00   512706.00
44165   SW08       Scotland  2024-25    898.95  474153.00   527454.00

[44166 rows x 6 columns]

In [24]:
#find rows with added data from new year
temp = new_df.rename({'Year': 'Year_new'}, axis=1)
#merged = temp.merge(old_df, how='left', left_on=['LocalAuthority','Code','Year_new'], right_on=['LocalAuthority','Code','Year'])
merged = temp.merge(old_df, how='left', left_on=['LocalAuthority','Year_new'], right_on=['LocalAuthority','Year'],indicator='Match')
new_year_df = np.where(merged['Year'].isnull())[0]
new_year_df

array([1923524, 1923525, 1923526, 1923527, 1923528, 1923529, 1923530,
       1945794, 1945795, 1945796, 1945797, 1945798, 1945799, 1945800])

# create a new data frame with just the new year's data

In [25]:
#new year added data
new_Data = pd.concat([old_df,new_df]).drop_duplicates(subset=["Code", "LocalAuthority", 'Year'], keep=False)

In [26]:
new_Data

        Code   LocalAuthority     Year Indicator Numerator Denominator
5965   CHN06            Moray  2020-21      0.41       nan         nan
5968   CHN06            Moray  2023-24      0.31       nan         nan
6246   CHN07      Eilean Siar  2016-17      0.00       nan         nan
6325   CHN07            Moray  2020-21      0.19       nan         nan
6359   CHN07  Perth & Kinross  2016-17      0.09       nan         nan
...      ...              ...      ...       ...       ...         ...
43131  CHN04         Scotland  2024-25      0.69       nan         nan
43145  CHN05         Scotland  2024-25      0.41       nan         nan
43159  CHN06         Scotland  2024-25      0.53       nan         nan
43173  CHN07         Scotland  2024-25      0.24       nan         nan
43243  CHN11         Scotland  2024-25      0.96       nan         nan

[187 rows x 6 columns]

In [27]:
from google.colab import files
new_Data. to_excel('new_Data.xlsx')
files.download('new_Data.xlsx')

#Use diff and new_Data to get the Change log