<a href="https://colab.research.google.com/github/LGBFBenchmarking/ChangeLogMaker/blob/main/Automate_differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Test code for automated output file

#Load files

##new_df is new data including new year's data
##diff_df has old data (no changes or new data for the new year)

In [1]:
import pandas as pd
import numpy as np

def get_data(url): # this function gets data stored as csv file from a given url
  df = pd.read_csv(url)
  return df

In [2]:
url_old = "https://raw.githubusercontent.com/LGBFBenchmarking/ChangeLogMaker/refs/heads/main/LGBF_Data_Mar26.csv"
url_new = "https://raw.githubusercontent.com/LGBFBenchmarking/ChangeLogMaker/refs/heads/main/LGBF_Data_Apr26.csv"
old_df = get_data(url_old)
new_df = get_data(url_new)

In [3]:
old_df.dtypes

Code               object
LocalAuthority     object
Year               object
Indicator         float64
Numerator         float64
Denominator       float64
dtype: object

In [4]:
new_df.dtypes

Code               object
LocalAuthority     object
Year               object
Indicator         float64
Numerator         float64
Denominator       float64
dtype: object

In [5]:
new_df['Indicator'] = new_df['Indicator'].map("{:.2f}".format)
new_df['Numerator'] = new_df['Numerator'].map('{:.2f}'.format)
new_df['Denominator'] = new_df['Denominator'].map('{:.2f}'.format)

In [6]:
old_df['Indicator'] = old_df['Indicator'].map('{:.2f}'.format)
old_df['Numerator'] = old_df['Numerator'].map('{:.2f}'.format)
old_df['Denominator'] = old_df['Denominator'].map('{:.2f}'.format)

In [7]:
old_df = old_df.round(4)
new_df = new_df.round(4)

In [8]:
old_df.head()

    Code LocalAuthority     Year Indicator Numerator Denominator
0  C&L01  Aberdeen City  2010-11      0.33    637.00  1922292.00
1  C&L01  Aberdeen City  2011-12      0.76   1554.00  2045051.00
2  C&L01  Aberdeen City  2012-13      3.64   7883.00  2163756.00
3  C&L01  Aberdeen City  2013-14      3.48   7726.00  2222588.00
4  C&L01  Aberdeen City  2014-15      3.02   7517.00  2487138.00

In [9]:
new_df.head()

    Code LocalAuthority     Year Indicator Numerator Denominator
0  C&L01  Aberdeen City  2010-11      0.33    637.00  1922292.00
1  C&L01  Aberdeen City  2011-12      0.76   1554.00  2045051.00
2  C&L01  Aberdeen City  2012-13      3.64   7883.00  2163756.00
3  C&L01  Aberdeen City  2013-14      3.48   7726.00  2222588.00
4  C&L01  Aberdeen City  2014-15      3.02   7517.00  2487138.00

In [10]:
df1 = old_df
df2 = new_df

In [11]:
new_set = df2[~df2.astype(str).apply(tuple, 1).isin(df1.astype(str).apply(tuple, 1))]

In [12]:
out = pd.merge(old_df, new_df, on=['Code', 'LocalAuthority', 'Year'], how='outer',
               suffixes=('_old', '_new')).set_index(['Code', 'LocalAuthority', 'Year'])

out.columns = pd.MultiIndex.from_tuples(out.columns.str.split('_').map(tuple)).swaplevel()
out

                                   old                             new  \
                             Indicator Numerator Denominator Indicator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11      0.33    637.00  1922292.00      0.33
                     2011-12      0.76   1554.00  2045051.00      0.76
                     2012-13      3.64   7883.00  2163756.00      3.64
                     2013-14      3.48   7726.00  2222588.00      3.48
                     2014-15      3.02   7517.00  2487138.00      3.02
...                                ...       ...         ...       ...
SW08  West Lothian   2020-21    369.62   4692.00    12694.00    369.62
                     2021-22    439.50   5750.00    13083.00    439.50
                     2022-23    639.84   8856.00    13841.00    639.84
                     2023-24    809.85  11742.00    14499.00    809.85
                     2024-25    960.18  14466.00    15066.00    960.18


                             Numerator Denominator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11    637.00  1922292.00
                     2011-12   1554.00  2045051.00
                     2012-13   7883.00  2163756.00
                     2013-14   7726.00  2222588.00
                     2014-15   7517.00  2487138.00
...                                ...         ...
SW08  West Lothian   2020-21   4692.00    12694.00
                     2021-22   5750.00    13083.00
                     2022-23   8856.00    13841.00
                     2023-24  11742.00    14499.00
                     2024-25  14466.00    15066.00

[44643 rows x 6 columns]

In [13]:
out = out.drop_duplicates(keep=False)
out

                                   old                             new  \
                             Indicator Numerator Denominator Indicator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11      0.33    637.00  1922292.00      0.33
                     2011-12      0.76   1554.00  2045051.00      0.76
                     2012-13      3.64   7883.00  2163756.00      3.64
                     2013-14      3.48   7726.00  2222588.00      3.48
                     2014-15      3.02   7517.00  2487138.00      3.02
...                                ...       ...         ...       ...
SW08  West Lothian   2020-21    369.62   4692.00    12694.00    369.62
                     2021-22    439.50   5750.00    13083.00    439.50
                     2022-23    639.84   8856.00    13841.00    639.84
                     2023-24    809.85  11742.00    14499.00    809.85
                     2024-25    960.18  14466.00    15066.00    960.18


                             Numerator Denominator
Code  LocalAuthority Year
C&L01 Aberdeen City  2010-11    637.00  1922292.00
                     2011-12   1554.00  2045051.00
                     2012-13   7883.00  2163756.00
                     2013-14   7726.00  2222588.00
                     2014-15   7517.00  2487138.00
...                                ...         ...
SW08  West Lothian   2020-21   4692.00    12694.00
                     2021-22   5750.00    13083.00
                     2022-23   8856.00    13841.00
                     2023-24  11742.00    14499.00
                     2024-25  14466.00    15066.00

[23621 rows x 6 columns]

In [14]:
new_set

          Code    LocalAuthority     Year Indicator  Numerator Denominator
6587    CHN08a     Aberdeen City  2024-25   5145.05   15785.00       59.00
6602    CHN08a     Aberdeenshire  2024-25   2880.97   14232.00       95.00
6617    CHN08a             Angus  2024-25   5741.52   10151.00       34.00
6632    CHN08a     Argyll & Bute  2024-25   3862.54    5423.00       27.00
6647    CHN08a  Clackmannanshire  2024-25   5483.17    4562.00       16.00
...        ...               ...      ...       ...        ...         ...
44062   ECON05          Scotland  2025-26     13.07    7250.00  5546900.00
44152  ECON12a          Scotland  2023-24      0.03  109140.00  3491476.00
44153  ECON12a          Scotland  2024-25      0.03  108550.00  3511191.00
44154  ECON12a          Scotland  2025-26      0.03  110500.00  3511191.00
44170  ECON12b          Scotland  2025-26      0.04   22035.00   592602.00

[381 rows x 6 columns]

In [15]:
from google.colab import files
new_set. to_excel('new_set.xlsx')
files.download('new_set.xlsx')

In [16]:
df1.merge(df2, on=['Code','LocalAuthority','Year'], suffixes=['_old','_new']).drop_duplicates(keep= False) # just a test no need to run this!!!

,Code,LocalAuthority,Year,Indicator_old,Numerator_old,Denominator_old,Indicator_new,Numerator_new,Denominator_new
0,C&L01,Aberdeen City,2010-11,0.33,637.00,1922292.00,0.33,637.00,1922292.00
1,C&L01,Aberdeen City,2011-12,0.76,1554.00,2045051.00,0.76,1554.00,2045051.00
2,C&L01,Aberdeen City,2012-13,3.64,7883.00,2163756.00,3.64,7883.00,2163756.00
3,C&L01,Aberdeen City,2013-14,3.48,7726.00,2222588.00,3.48,7726.00,2222588.00
4,C&L01,Aberdeen City,2014-15,3.02,7517.00,2487138.00,3.02,7517.00,2487138.00
...,...,...,...,...,...,...,...,...,...
44440,SW08,Scotland,2020-21,485.45,227524.00,468682.00,485.45,227524.00,468682.00
44441,SW08,Scotland,2021-22,749.73,357719.00,477131.00,749.73,357719.00,477131.00
44442,SW08,Scotland,2022-23,882.88,439596.00,497909.00,882.88,439596.00,497909.00
44443,SW08,Scotland,2023-24,841.47,431429.00,512706.00,841.47,431429.00,512706.00
44444,SW08,Scotland,2024-25,898.95,474153.00,527454.00,898.95,474153.00,527454.00

In [17]:
def dataframe_difference(df1, df2, which=None):
    """Find rows which are different between two DataFrames."""
    comparison_df = df1.merge(
        df2,
        indicator=True,
        how='outer'
    )
    if which is None:
        diff_df = comparison_df[comparison_df['_merge'] != 'both']  # Identify data changes/updates
    else:
        diff_df = comparison_df[comparison_df['_merge'] == which]
    return diff_df

In [18]:
def getColChangedName(row):
    colsChanged = []
    for c in df1.columns.values:
        if row[c+"_diff"] == True:
            colsChanged.append(c)
    return ", ".join(colsChanged)

In [19]:
df1 = old_df.set_index(['Code', 'LocalAuthority', 'Year'])
df2 = new_set.set_index(['Code','LocalAuthority', 'Year'])

diffs = df1.merge(df2, left_index=True, right_index=True, suffixes=('_old', '_new'))

diff_cols = [c+"_diff" for c in df1.columns.values]

for c in df1.columns.values:
    diffs[c+"_diff"] = diffs[c+"_old"] != diffs[c+"_new"]

diffs["Record_Changed"] = diffs[diff_cols].sum(axis=1)/len(diff_cols) > 0


diffs = diffs[diffs["Record_Changed"] == 1]
diffs["Cols_Changed"] = diffs.apply(lambda row: getColChangedName(row), axis=1)

diffs

                                 Indicator_old Numerator_old Denominator_old  \
Code    LocalAuthority   Year
CHN08a  Aberdeen City    2024-25           nan           nan             nan
        Aberdeenshire    2024-25           nan           nan             nan
        Angus            2024-25           nan           nan             nan
        Argyll & Bute    2024-25           nan           nan             nan
        Clackmannanshire 2024-25           nan           nan             nan
...                                        ...           ...             ...
ECON05  Scotland         2022-23         14.42       7853.00      5447000.00
                         2023-24         13.53       7451.00      5506000.00
                         2024-25         12.26       6799.00      5546900.00
ECON12a Scotland         2023-24          0.03     109135.00      3491476.00
                         2024-25          0.03     108540.00      3511191.00

                                 Indicator_new Numerator_new Denominator_new  \
Code    LocalAuthority   Year
CHN08a  Aberdeen City    2024-25       5145.05      15785.00           59.00
        Aberdeenshire    2024-25       2880.97      14232.00           95.00
        Angus            2024-25       5741.52      10151.00           34.00
        Argyll & Bute    2024-25       3862.54       5423.00           27.00
        Clackmannanshire 2024-25       5483.17       4562.00           16.00
...                                        ...           ...             ...
ECON05  Scotland         2022-23         14.41       7850.00      5447000.00
                         2023-24         13.53       7449.00      5506000.00
                         2024-25         13.43       7449.00      5546900.00
ECON12a Scotland         2023-24          0.03     109140.00      3491476.00
                         2024-25          0.03     108550.00      3511191.00

                                  Indicator_diff  Numerator_diff  \
Code    LocalAuthority   Year
CHN08a  Aberdeen City    2024-25            True            True
        Aberdeenshire    2024-25            True            True
        Angus            2024-25            True            True
        Argyll & Bute    2024-25            True            True
        Clackmannanshire 2024-25            True            True
...                                          ...             ...
ECON05  Scotland         2022-23            True            True
                         2023-24           False            True
                         2024-25            True            True
ECON12a Scotland         2023-24           False            True
                         2024-25           False            True

                                  Denominator_diff  Record_Changed  \
Code    LocalAuthority   Year
CHN08a  Aberdeen City    2024-25              True            True
        Aberdeenshire    2024-25              True            True
        Angus            2024-25              True            True
        Argyll & Bute    2024-25              True            True
        Clackmannanshire 2024-25              True            True
...                                            ...             ...
ECON05  Scotland         2022-23             False            True
                         2023-24             False            True
                         2024-25             False            True
ECON12a Scotland         2023-24             False            True
                         2024-25             False            True

                                                       Cols_Changed
Code    LocalAuthority   Year
CHN08a  Aberdeen City    2024-25  Indicator, Numerator, Denominator
        Aberdeenshire    2024-25  Indicator, Numerator, Denominator
        Angus            2024-25  Indicator, Numerator, Denominator
        Argyll & Bute    2024-25  Indicator, Numerator, Denominator
        Clackmannanshire 2024-25  Indicator, Numerator, Denominator
...                                                             ...
ECON05  Scotland         2022-23               Indicator, Numerator
                         2023-24                          Numerator
                         2024-25               Indicator, Numerator
ECON12a Scotland         2023-24                          Numerator
                         2024-25                          Numerator

[183 rows x 11 columns]

In [20]:
from google.colab import files
diffs. to_excel('diffs.xlsx')
files.download('diffs.xlsx')

In [21]:
old_df

        Code LocalAuthority     Year Indicator  Numerator Denominator
0      C&L01  Aberdeen City  2010-11      0.33     637.00  1922292.00
1      C&L01  Aberdeen City  2011-12      0.76    1554.00  2045051.00
2      C&L01  Aberdeen City  2012-13      3.64    7883.00  2163756.00
3      C&L01  Aberdeen City  2013-14      3.48    7726.00  2222588.00
4      C&L01  Aberdeen City  2014-15      3.02    7517.00  2487138.00
...      ...            ...      ...       ...        ...         ...
44440   SW08       Scotland  2020-21    485.45  227524.00   468682.00
44441   SW08       Scotland  2021-22    749.73  357719.00   477131.00
44442   SW08       Scotland  2022-23    882.88  439596.00   497909.00
44443   SW08       Scotland  2023-24    841.47  431429.00   512706.00
44444   SW08       Scotland  2024-25    898.95  474153.00   527454.00

[44445 rows x 6 columns]

In [22]:
temp = new_df.rename({'Year': 'Year_new'}, axis=1)
temp

        Code LocalAuthority Year_new Indicator  Numerator Denominator
0      C&L01  Aberdeen City  2010-11      0.33     637.00  1922292.00
1      C&L01  Aberdeen City  2011-12      0.76    1554.00  2045051.00
2      C&L01  Aberdeen City  2012-13      3.64    7883.00  2163756.00
3      C&L01  Aberdeen City  2013-14      3.48    7726.00  2222588.00
4      C&L01  Aberdeen City  2014-15      3.02    7517.00  2487138.00
...      ...            ...      ...       ...        ...         ...
44638   SW08       Scotland  2020-21    485.45  227524.00   468682.00
44639   SW08       Scotland  2021-22    749.73  357719.00   477131.00
44640   SW08       Scotland  2022-23    882.88  439596.00   497909.00
44641   SW08       Scotland  2023-24    841.47  431429.00   512706.00
44642   SW08       Scotland  2024-25    898.95  474153.00   527454.00

[44643 rows x 6 columns]

In [23]:
old_df

        Code LocalAuthority     Year Indicator  Numerator Denominator
0      C&L01  Aberdeen City  2010-11      0.33     637.00  1922292.00
1      C&L01  Aberdeen City  2011-12      0.76    1554.00  2045051.00
2      C&L01  Aberdeen City  2012-13      3.64    7883.00  2163756.00
3      C&L01  Aberdeen City  2013-14      3.48    7726.00  2222588.00
4      C&L01  Aberdeen City  2014-15      3.02    7517.00  2487138.00
...      ...            ...      ...       ...        ...         ...
44440   SW08       Scotland  2020-21    485.45  227524.00   468682.00
44441   SW08       Scotland  2021-22    749.73  357719.00   477131.00
44442   SW08       Scotland  2022-23    882.88  439596.00   497909.00
44443   SW08       Scotland  2023-24    841.47  431429.00   512706.00
44444   SW08       Scotland  2024-25    898.95  474153.00   527454.00

[44445 rows x 6 columns]

In [24]:
#find rows with added data from new year
temp = new_df.rename({'Year': 'Year_new'}, axis=1)
#merged = temp.merge(old_df, how='left', left_on=['LocalAuthority','Code','Year_new'], right_on=['LocalAuthority','Code','Year'])
merged = temp.merge(old_df, how='left', left_on=['LocalAuthority','Year_new'], right_on=['LocalAuthority','Year'],indicator='Match')
new_year_df = np.where(merged['Year'].isnull())[0]
new_year_df

array([2292175, 2293269, 2294364, 2295403, 2296489, 2297533, 2298628,
       2299723, 2300817, 2301907, 2302995, 2304089, 2305053, 2306145,
       2307240, 2308284, 2309370, 2310411, 2311502, 2312568, 2313660,
       2314755, 2315786, 2316880, 2317974, 2319017, 2320033, 2321126,
       2322221, 2323313, 2324405, 2325500, 2546625, 2547990, 2549359,
       2550668, 2552028, 2553342, 2554711, 2556080, 2557448, 2558811,
       2560173, 2561540, 2562760, 2564126, 2565495, 2566809, 2568169,
       2569480, 2570845, 2572180, 2573546, 2574915, 2576208, 2577576,
       2578944, 2580255, 2581532, 2582899, 2584268, 2585634, 2587000,
       2588369, 2589734, 2591099, 2592468, 2593777, 2595137, 2596451,
       2597820, 2599189, 2600557, 2601920, 2603282, 2604649, 2605869,
       2607235, 2608604, 2609918, 2611278, 2612589, 2613954, 2615289,
       2616655, 2618024, 2619317, 2620685, 2622053, 2623364, 2624641,
       2626008, 2627377, 2628743, 2630109, 2631478, 4062397, 4071028,
       4072397])

# create a new data frame with just the new year's data

In [25]:
#new year added data
new_Data = pd.concat([old_df,new_df]).drop_duplicates(subset=["Code", "LocalAuthority", 'Year'], keep=False)

In [26]:
new_Data

          Code    LocalAuthority     Year Indicator  Numerator Denominator
7547     CHN09     Aberdeen City  2024-25      0.87        nan         nan
7562     CHN09     Aberdeenshire  2024-25      0.76        nan         nan
7577     CHN09             Angus  2024-25      0.87        nan         nan
7592     CHN09     Argyll & Bute  2024-25      0.79        nan         nan
7607     CHN09  Clackmannanshire  2024-25      0.93        nan         nan
...        ...               ...      ...       ...        ...         ...
43668    CHN17          Scotland  2024-25      0.83        nan         nan
43738    CHN22          Scotland  2024-25      0.07        nan         nan
44062   ECON05          Scotland  2025-26     13.07    7250.00  5546900.00
44154  ECON12a          Scotland  2025-26      0.03  110500.00  3511191.00
44170  ECON12b          Scotland  2025-26      0.04   22035.00   592602.00

[198 rows x 6 columns]

In [27]:
from google.colab import files
new_Data. to_excel('new_Data.xlsx')
files.download('new_Data.xlsx')

#Use diff and new_Data to get the Change log